const vocabList_first = {
  vocabList_u_26: [
    { jp: "見る（みます）", vn: "xem, nhìn" },
    { jp: "診る（みます）", vn: "chẩn đoán, khám bệnh" },
    { jp: "捜す（さがします）", vn: "tìm đồ vật bị mất" },
    { jp: "探す（さがします）", vn: "tìm, tìm kiếm (cv, người…)" },
    { jp: "遅れる（おくれます）", vn: "trễ giờ" },
    { jp: "間に合います（まにあいます）", vn: "kịp giờ" },
    { jp: "宿題をやります（やります）", vn: "làm bài tập" },
    { jp: "拾います（ひろいます）", vn: "nhặt rác" },
    { jp: "連絡します（れんらくします）", vn: "liên lạc với trường học" },
    { jp: "気分がいい（きぶんがいい）", vn: "tâm trạng, thể trạng tốt" },
    { jp: "気分が悪い（きぶんがわるい）", vn: "tâm trạng, thể trạng xấu" },
    { jp: "運動会（うんどうかい）", vn: "hội thi thể thao" },
    { jp: "盆踊り（ぼんおどり）", vn: "lễ hội múa obon" },
    { jp: "フリーマーケット", vn: "chợ đồ cũ, chợ trời" },
    { jp: "場所（ばしょ）", vn: "nơi chốn, địa điểm" },
    { jp: "ボランティア", vn: "việc từ thiện, tình nguyện viên" },
    { jp: "財布（さいふ）", vn: "ví" },
    { jp: "ごみ", vn: "rác" },
    { jp: "国会議事堂（こっかいぎじどう）", vn: "tòa nhà quốc hội" },
    { jp: "平日（へいじつ）", vn: "ngày thường" },
    { jp: "大阪弁（おおさかべん）", vn: "tiếng Osaka, tiếng địa phương" },
    { jp: "今度（こんど）", vn: "lần tới" },
    { jp: "ずいぶん", vn: "khá, tương đối" },
    { jp: "直接（ちょくせつ）", vn: "trực tiếp" },
    { jp: "いつでも", vn: "lúc nào cũng" },
    { jp: "どこでも", vn: "ở đâu cũng" },
    { jp: "だれでも", vn: "ai cũng" },
    { jp: "なんでも", vn: "cái gì cũng" },
    { jp: "こんな…", vn: "...như thế này" },
    { jp: "そんな…", vn: "...như thế đó" },
    { jp: "あんな…", vn: "...như thế kia" },
    { jp: "片付く（かたづきます）", vn: "sắp xếp, dọn dẹp" },
    { jp: "出す（だします）", vn: "đổ, để (rác)" },
    { jp: "燃えるごみ（もえるごみ）", vn: "rác cháy được" },
    { jp: "置き場（おきば）", vn: "chỗ để, chỗ đặt" },
    { jp: "横（よこ）", vn: "bên cạnh" },
    { jp: "瓶（びん）", vn: "cái chai" },
    { jp: "缶（かん）", vn: "cái lon, hộp kim loại" },
    { jp: "ガス", vn: "ga" },
    { jp: "ガス会社（ガスがいしゃ）", vn: "công ty ga" },
    { jp: "宇宙（うちゅう）", vn: "vũ trụ" },
    { jp: "様（さま）", vn: "ngài, vị" },
    { jp: "宇宙船（うちゅうせん）", vn: "tàu vũ trụ" },
    { jp: "怖い（こわい）", vn: "sợ, đáng sợ" },
    { jp: "違います（ちがいます）", vn: "khác, không phải" },
    { jp: "宇宙飛行士（うちゅうひこうし）", vn: "nhà du hành vũ trụ" }
  ],
  vocabList_u_27: [
    { jp: "飼います（かいます）", vn: "nuôi, chăn nuôi" },
    { jp: "建てます（たてます）", vn: "xây dựng" },
    { jp: "走ります（はしります）", vn: "chạy" },
    { jp: "取ります（とります）", vn: "xin (nghỉ)" },
    { jp: "見えます（みえます）", vn: "có thể nhìn thấy" },
    { jp: "聞こえます（きこえます）", vn: "có thể nghe thấy" },
    { jp: "できます", vn: "được hoàn thành, được làm" },
    { jp: "開きます（ひらきます）", vn: "mở, tổ chức (lớp)" },
    { jp: "ペット", vn: "thú cưng, động vật nuôi" },
    { jp: "鳥（とり）", vn: "chim" },
    { jp: "こえ", vn: "tiếng, giọng nói" },
    { jp: "波（なみ）", vn: "sóng" },
    { jp: "花火（はなび）", vn: "pháo hoa" },
    { jp: "景色（けしき）", vn: "phong cảnh" },
    { jp: "昼間（ひるま）", vn: "ban ngày" },
    { jp: "昔（むかし）", vn: "ngày xưa" },
    { jp: "道具（どうぐ）", vn: "dụng cụ" },
    { jp: "自動販売機（じどうはんばいき）", vn: "máy bán hàng tự động" },
    { jp: "通信販売（つうしんはんばい）", vn: "thương mại viễn thông" },
    { jp: "クリーニング", vn: "giặt ủi" },
    { jp: "マンション", vn: "chung cư" },
    { jp: "台所（だいどころ）", vn: "nhà bếp" },
    { jp: "～後（～ご）", vn: "sau…" },
    { jp: "～しか", vn: "chỉ" },
    { jp: "～教室（～きょうしつ）", vn: "lớp học" },
    { jp: "パーティールーム", vn: "phòng tiệc" },
    { jp: "関西空港（かんさいくうこう）", vn: "sân bay Kansai" },
    { jp: "秋葉原（あきはばら）", vn: "khu bán đồ điện tử nổi tiếng ở Tokyo" },
    { jp: "伊豆（いず）", vn: "một đảo thuộc tỉnh Shizuoka" },
    { jp: "日曜日大工（にちようびだいく）", vn: "thợ mộc chủ nhật" },
    { jp: "本棚（ほんだな）", vn: "kệ sách, giá sách" },
    { jp: "いつか", vn: "một ngày nào đó" },
    { jp: "夢（ゆめ）", vn: "mơ" },
    { jp: "家（いえ）", vn: "nhà" },
    { jp: "素晴らしい（すばらしい）", vn: "tuyệt vời" },
    { jp: "子どもたち（こどもたち）", vn: "bọn trẻ" },
    { jp: "大好き（だいすき）", vn: "rất thích" },
    { jp: "漫画（まんが）", vn: "truyện tranh" },
    { jp: "主人公（しゅじんこう）", vn: "nhân vật chính" },
    { jp: "形（かたち）", vn: "hình dạng" },
    { jp: "ロボット", vn: "người máy" },
    { jp: "不思議な（ふしぎな）", vn: "kì lạ, thần bí" },
    { jp: "ポケット", vn: "túi" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "付けます（つけます）", vn: "lắp ghép" },
    { jp: "自由に（じゆうに）", vn: "tự do" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "飛びます（とびます）", vn: "bay" },
    { jp: "自分（じぶん）", vn: "tự mình" },
    { jp: "将来（しょうらい）", vn: "tương lai" },
    { jp: "他の / 外の（ほかの）", vn: "...khác" },
    { jp: "はっきり ", vn: "rõ ràng" }
  ],
  vocabList_u_28: [
    { jp: "売れます（うれます）", vn: "bán" },
    { jp: "踊ります（おどります）", vn: "nhảy" },
    { jp: "噛みます（かみます）", vn: "nhai, cắn" },
    { jp: "選びます（えらびます）", vn: "lựa, lựa chọn" },
    { jp: "通います（かよいます）", vn: "đi học (đại học)" },
    { jp: "メモします", vn: "ghi chép lại, ghi lại" },
    { jp: "真面目（まじめ）", vn: "nghiêm túc, đàng hoàng" },
    { jp: "熱心（ねっしん）", vn: "nhiệt tình" },
    { jp: "偉い（えらい）", vn: "vĩ đại, kính trọng" },
    { jp: "丁度いい（ちょうどいい）", vn: "vừa đúng, vừa vặn" },
    { jp: "優しい（やさしい）", vn: "hiền lành" },
    { jp: "習慣（しゅうかん）", vn: "tập quán" },
    { jp: "経験（けいけん）", vn: "kinh nghiệm" },
    { jp: "力（ちから）", vn: "sức mạnh" },
    { jp: "人気（にんき）", vn: "hâm mộ" },
    { jp: "形（かたち）", vn: "hình dáng" },
    { jp: "色（いろ）", vn: "màu sắc" },
    { jp: "味（あじ）", vn: "vị" },
    { jp: "ガム", vn: "kẹo cao su" },
    { jp: "品物（しなもの）", vn: "hàng hóa" },
    { jp: "値段（ねだん）", vn: "giá cả" },
    { jp: "給料（きゅうりょう）", vn: "lương" },
    { jp: "ボーナス", vn: "thưởng" },
    { jp: "番組（ばんぐみ）", vn: "chương trình (TV, phát thanh...)" },
    { jp: "ドラマ", vn: "kịch, phim truyền hình" },
    { jp: "小説（しょうせつ）", vn: "tiểu thuyết" },
    { jp: "小説家（しょうせつか）", vn: "tiểu thuyết gia" },
    { jp: "歌手（かしゅ）", vn: "ca sĩ" },
    { jp: "管理人（かんりにん）", vn: "người quản lý" },
    { jp: "息子（むすこ）", vn: "con trai (mình)" },
    { jp: "息子さん（むすこさん）", vn: "con trai (người khác)" },
    { jp: "娘（むすめ）", vn: "con gái (mình)" },
    { jp: "娘さん（むすめさん）", vn: "con gái (người khác)" },
    { jp: "自分（じぶん）", vn: "bản thân" },
    { jp: "将来（しょうらい）", vn: "tương lai" },
    { jp: "しばらく", vn: "một lát, một chút" },
    { jp: "たいてい", vn: "thường, thông thường" },
    { jp: "それに", vn: "ngoài ra" },
    { jp: "それで", vn: "do đó" },
    { jp: "「ちょっと」お願いがあるんですが", vn: "tôi có chút việc muốn nhờ" },
    { jp: "ホームステイ", vn: "homestay" },
    { jp: "会話（かいわ）", vn: "hội thoại" },
    { jp: "おしゃべりします", vn: "trò chuyện" },
    { jp: "お知らせ（おしらせ）", vn: "thông báo" },
    { jp: "日にち（ひにち）", vn: "ngày" },
    { jp: "土（ど）", vn: "thứ bảy" },
    { jp: "体育館（たいいくかん）", vn: "phòng thể dục" },
    { jp: "無料（むりょう）", vn: "miễn phí" },
  ],
  vocabList_u_29: [
    { jp: "開きます（あきます）", vn: "mở (cửa)" },
    { jp: "閉まります（しまります）", vn: "đóng (cửa)" },
    { jp: "点きます（つきます）", vn: "bật, sáng (đèn)" },
    { jp: "消えます（きえます）", vn: "tắt (đèn)" },
    { jp: "込みます（こみます）", vn: "đông (đường)" },
    { jp: "空きます（すきます）", vn: "vắng (đường)" },
    { jp: "壊れます（こわれます）", vn: "hỏng (ghế)" },
    { jp: "割れます（われます）", vn: "vỡ (cốc)" },
    { jp: "折れます（おれます）", vn: "gãy (cây)" },
    { jp: "破れます（やぶれます）", vn: "rách (giấy)" },
    { jp: "汚れます（よごれます）", vn: "dơ, bẩn (tay)" },
    { jp: "付きます（つきます）", vn: "dính, đính (có túi)" },
    { jp: "外れます（はずれます）", vn: "tuột, rời ra (nút)" },
    { jp: "止まります（とまります）", vn: "dừng" },
    { jp: "間違えます（まちがえます）", vn: "nhầm lẫn, sai" },
    { jp: "落とします（おとします）", vn: "làm rơi, rớt" },
    { jp: "掛かります（かかります）", vn: "khóa (đang bị khóa)" },
    { jp: "拭きます（ふきます）", vn: "lau (cửa)" },
    { jp: "取り替えます（とりかえます）", vn: "thay (pin)" },
    { jp: "片付けます（かたづけます）", vn: "dọn dẹp" },
    { jp: "皿（さら）", vn: "đĩa" },
    { jp: "茶碗（ちゃわん）", vn: "bát, chén" },
    { jp: "コップ", vn: "cốc" },
    { jp: "ガラス", vn: "ly (thủy tinh)" },
    { jp: "袋（ふくろ）", vn: "túi" },
    { jp: "書類（しょるい）", vn: "giấy tờ" },
    { jp: "枝（えだ）", vn: "cành cây" },
    { jp: "駅員（えきいん）", vn: "nhân viên nhà ga" },
    { jp: "交番（こうばん）", vn: "đồn cảnh sát" },
    { jp: "スピーチ", vn: "bài diễn văn" },
    { jp: "返事（へんじ）", vn: "trả lời" },
    { jp: "お先にどうぞ（おさきにどうぞ）", vn: "mời anh/chị cứ về trước" },
    { jp: "源氏物語（げんじものがたり）", vn: "Truyện Genji" },
    { jp: "今の電車（いまのでんしゃ）", vn: "tàu điện vừa chạy" },
    { jp: "忘れ物（わすれもの）", vn: "đồ bỏ quên" },
    { jp: "このくらい", vn: "cỡ tầm này" },
    { jp: "側（がわ）", vn: "phía..." },
    { jp: "ポケット", vn: "túi (quần áo)" },
    { jp: "辺（へん）", vn: "chỗ, vùng" },
    { jp: "覚えていません（おぼえていません）", vn: "tôi không nhớ" },
    { jp: "網棚（あみだな）", vn: "giá để hành lý" },
    { jp: "確か（たしか）", vn: "chắc là" },
    { jp: "ああ、よかった", vn: "ôi, may quá" },
    { jp: "地震（じしん）", vn: "động đất" },
    { jp: "壁（かべ）", vn: "bức tường" },
    { jp: "針（はり）", vn: "kim đồng hồ" },
    { jp: "指します（さします）", vn: "chỉ" },
    { jp: "駅前（えきまえ）", vn: "trước ga" },
    { jp: "倒れます（たおれます）", vn: "đổ (ngã, sập...)" },
    { jp: "西の方（にしのほう）", vn: "phía tây" },
    { jp: "燃えます（もえます）", vn: "cháy" }
  ],
  vocabList_u_30: [
    { jp: "はります", vn: "dán" },
    { jp: "掛けます（かけます）", vn: "treo" },
    { jp: "飾ります（かざります）", vn: "trang trí" },
    { jp: "並べます（ならべます）", vn: "xếp thành hàng" },
    { jp: "植えます（うえます）", vn: "trồng (cây)" },
    { jp: "戻します（もどします）", vn: "đưa về, trả về" },
    { jp: "まとめます", vn: "nhóm lại, tóm tắt" },
    { jp: "方づけます（かたづけます）", vn: "dọn dẹp, sắp xếp" },
    { jp: "しまいます", vn: "cất vào, để vào" },
    { jp: "決めます（きめます）", vn: "quyết định" },
    { jp: "知らせます（しらせます）", vn: "thông báo" },
    { jp: "祖横断します（そうだんします）", vn: "thảo luận, trao đổi , bàn bạc" },
    { jp: "予習します（よしゅうします）", vn: "chuẩn bị bài mới" },
    { jp: "復習します（ふくしゅうします）", vn: "ôn bài cũ" },
    { jp: "そのままにします", vn: "để nguyên như thế" },
    { jp: "お子さん（おこさん）", vn: "con (dùng đối với người khác)" },
    { jp: "授業（じゅぎょう）", vn: "giờ học" },
    { jp: "講義（こうぎ）", vn: "bài giảng" },
    { jp: "ミーティング", vn: "cuộc họp" },
    { jp: "予定（よてい）", vn: "kế hoạch, dự định" },
    { jp: "お知らせ（おしらせ）", vn: "bản thông báo" },
    { jp: "案内書（あんないしょ）", vn: "tài liệu hướng dẫn" },
    { jp: "カレンダー", vn: "lịch , tờ lịch" },
    { jp: "ポスター", vn: "tờ quảng cáo, tờ áp phích" },
    { jp: "ごみ箱（ごみばこ）", vn: "thùng rác" },
    { jp: "人形（にんぎょう）", vn: "con búp bê, con rối" },
    { jp: "花瓶（かびん）", vn: "lọ hoa" },
    { jp: "鏡（かがみ）", vn: "cái gương" },
    { jp: "引き出し（ひきだし）", vn: "ngăn kéo" },
    { jp: "玄関（げんかん）", vn: "cửa vào" },
    { jp: "廊下（ろうか）", vn: "hành lang" },
    { jp: "壁（かべ）", vn: "bức tường" },
    { jp: "池（いけ）", vn: "cái ao" },
    { jp: "交番（こうばん）", vn: "trạm cảnh sát" },
    { jp: "元の所（もとのところ）", vn: "địa điểm ban đầu" },
    { jp: "周り（まわり）", vn: "xung quanh" },
    { jp: "真ん中（まんなか）", vn: "giữa, trung tâm" },
    { jp: "すみ", vn: "góc" },
    { jp: "まだ", vn: "chưa" },
    { jp: "―ほど", vn: "chừng—" },
    { jp: "予定表（よていひょう）", vn: "thời khóa biểu" },
    { jp: "ご苦労さま（ごくろうさま）", vn: "anh, chị đã làm việc vất vả/cảm ơn anh, chị" },
    { jp: "希望（きぼう）", vn: "hi vọng, nguyện vọng" },
    { jp: "何かご希望がありますか（なにかごきぼうがありますか）", vn: "anh/chị có nguyện vọng gì không?" },
    { jp: "ミュージカル", vn: "ca kịch" },
    { jp: "それはいいですな", vn: "Hay quá nhỉ" },
    { jp: "丸い（まるい）", vn: "tròn" },
    { jp: "月（つき）", vn: "mặt trăng" },
    { jp: "地球（ちきゅう）", vn: "trái đất" },
    { jp: "うれしい", vn: "vui" },
    { jp: "いや（な）", vn: "chán, ghét, không chấp nhận được" },
    { jp: "すると", vn: "sau đó, tiếp đó" },
    { jp: "目が覚めます（めがさめます）", vn: "tỉnh giấc, mở mắt" }
  ],
  vocabList_u_31: [
    { jp: "始まります（はじまります）", vn: "bắt đầu (buổi lễ ~)" },
    { jp: "続けます（つづけます）", vn: "tiếp tục" },
    { jp: "見つめます（みつけます）", vn: "tìm thấy" },
    { jp: "受けます（うけます）", vn: "thi (kì thi)" },
    { jp: "入学します（にゅうがくします）", vn: "nhập học" },
    { jp: "卒業します（そつぎょうします）", vn: "tốt nghiệp" },
    { jp: "休憩します（きゅうけいします）", vn: "giải lao" },
    { jp: "連休（れんきゅう）", vn: "ngày nghỉ liền nhau" },
    { jp: "作文（さくぶん）", vn: "bài văn" },
    { jp: "展覧会（てんらんかい）", vn: "triển lãm" },
    { jp: "結婚式（けっこんしき）", vn: "lễ cưới, đám cưới" },
    { jp: "葬式（そうしき）", vn: "lễ tang, đám tang" },
    { jp: "式（しき）", vn: "buổi lễ" },
    { jp: "本社（ほんしゃ）", vn: "trụ sở chính" },
    { jp: "支店（してん）", vn: "chi nhánh" },
    { jp: "教会（きょうかい）", vn: "nhà thờ" },
    { jp: "大学院（だいがくいん）", vn: "cao học, cơ sở giáo dục trên đại học" },
    { jp: "動物園（どうぶつえん）", vn: "sở thú" },
    { jp: "温泉（おんせん）", vn: "suối nước nóng" },
    { jp: "お客さん（おきゃくさん）", vn: "khách hàng" },
    { jp: "だれか", vn: "ai đó" },
    { jp: "～の方（～のほう）", vn: "hướng~" },
    { jp: "ずっと", vn: "suốt, liền" },
    { jp: "残ります（のこります）", vn: "ở lại, còn" },
    { jp: "月に（つきに）", vn: "(trong) một tháng" },
    { jp: "普通の（ふつうの）", vn: "thường" },
    { jp: "インターネット", vn: "internet" },
    { jp: "村（むら）", vn: "làng" },
    { jp: "映画館（えいがかん）", vn: "rạp chiếu phim" },
    { jp: "いや（な）", vn: "chán ghét, không chấp nhận được" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "閉じます（とじます）", vn: "nhắm" },
    { jp: "都会（とかい）", vn: "thành phố" },
    { jp: "子供たち（こどもたち）", vn: "bọn trẻ" },
    { jp: "自由に（じゆうに）", vn: "tự do" },
    { jp: "世界中（せかいじゅう）", vn: "khắp thế giới" },
    { jp: "集まります（あつまります）", vn: "tập hợp" },
    { jp: "美しい（うつくしい）", vn: "đẹp" },
    { jp: "自然（しぜん）", vn: "thiên nhiên, tự nhiên" },
    { jp: "すばらしさ", vn: "tuyệt vời" },
    { jp: "気が付きます（きがつきます）", vn: "để ý, nhận ra" }
  ],
  vocabList_u_32: [
    { jp: "運動します（うんどうします）", vn: "vận động, tập thể thao" },
    { jp: "成功します（せいこうします）", vn: "thành công" },
    { jp: "失敗します（しっぱいします）", vn: "thất bại, trượt" },
    { jp: "合格します（ごうかくします）", vn: "đỗ" },
    { jp: "戻ります（もどります）", vn: "quay lại, trở lại" },
    { jp: "やみます（雨が～）", vn: "tạnh, ngừng" },
    { jp: "晴れます（はれます）", vn: "nắng, quang đãng" },
    { jp: "曇ります（くもります）", vn: "có mây, mây mù" },
    { jp: "吹きます（ふきます）", vn: "thổi" },
    { jp: "治ります・直ります（なおります）", vn: "khỏi" },
    { jp: "続きます（つづきます）", vn: "tiếp tục, tiếp diễn" },
    { jp: "冷やします（ひやします）", vn: "làm lạnh" },
    { jp: "心配（しんぱい）", vn: "lo lắng" },
    { jp: "十分（じゅうぶん）", vn: "đủ" },
    { jp: "おかしい", vn: "có vấn đề, không bình thường" },
    { jp: "うるさい", vn: "ồn ào" },
    { jp: "やけど", vn: "bỏng" },
    { jp: "けが", vn: "bị thương" },
    { jp: "せき", vn: "ho" },
    { jp: "インフルエンザ", vn: "cúm dịch" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "太陽（たいよう）", vn: "mặt trời" },
    { jp: "星（ほし）", vn: "ngôi sao" },
    { jp: "月（つき）", vn: "mặt trăng" },
    { jp: "風（かぜ）", vn: "gió" },
    { jp: "北（きた）", vn: "phía bắc" },
    { jp: "南（みなみ）", vn: "phía nam" },
    { jp: "西（にし）", vn: "phía tây" },
    { jp: "東（ひがし）", vn: "phía đông" },
    { jp: "隧道（すいどう）", vn: "nước máy" },
    { jp: "エンジン", vn: "động cơ" },
    { jp: "チーム", vn: "đội" },
    { jp: "今夜（こんや）", vn: "tối nay, đêm nay" },
    { jp: "夕方（ゆうがた）", vn: "chiều tối" },
    { jp: "前（まえ）", vn: "trước" },
    { jp: "遅く（おそく）", vn: "muộn, khuya" },
    { jp: "こんなに", vn: "như thế này" },
    { jp: "そんなに", vn: "như thế đó" },
    { jp: "あんなに", vn: "như thế kia" },
    { jp: "もしかしたら", vn: "có thể, biết đâu là, có khả năng" },
    { jp: "それはいけませんね", vn: "thế thì thật không tốt" },
    { jp: "オリンピック", vn: "Olympic" },
    { jp: "元気（げんき）", vn: "khỏe mạnh" },
    { jp: "胃（い）", vn: "dạ dày" },
    { jp: "働きすぎ（はたらきすぎ）", vn: "làm việc quá sức" },
    { jp: "ストレス", vn: "căng thẳng tâm lý" },
    { jp: "無理をします（むりをします）", vn: "làm quá sức" },
    { jp: "ゆっくりします", vn: "nghỉ ngơi, thư thái, dưỡng sức" },
    { jp: "星占い（ほしうらない）", vn: "bói sao" },
    { jp: "牡牛座（おうしざ）", vn: "chòm sao Kim Ngưu" },
    { jp: "困ります（こまります）", vn: "rắc rối, khó xử, có vấn đề" },
    { jp: "宝くじ（たからくじ）", vn: "xổ số" },
    { jp: "当たります（あたります）", vn: "trúng (số)" },
    { jp: "健康（けんこう）", vn: "sức khỏe" },
    { jp: "恋愛（れんあい）", vn: "tình yêu" },
    { jp: "恋人（こいびと）", vn: "người yêu" },
    { jp: "金持ち（かねもち）", vn: "người giàu có" }
  ],
  vocabList_u_33: [
    { jp: "逃げます（にげます）", vn: "chạy trốn, bỏ chạy" },
    { jp: "騒ぎます（さわぎます）", vn: "làm ồn, làm rùm beng" },
    { jp: "あきらめます", vn: "từ bỏ, đầu hàng" },
    { jp: "投げます（なげます）", vn: "ném" },
    { jp: "守ります（まもります）", vn: "bảo vệ, tuân thủ" },
    { jp: "上げます（あげます）", vn: "nâng lên, tăng lên" },
    { jp: "下げます（さげます）", vn: "hạ xuống, giảm xuống" },
    { jp: "伝えます（つたえます）", vn: "truyền đạt" },
    { jp: "注意します（ちゅういします）", vn: "chú ý" },
    { jp: "外します（はずします）", vn: "rời, không có ở (chỗ ngồi)" },
    { jp: "だめ", vn: "không được, không thể" },
    { jp: "席（せき）", vn: "chỗ ngồi, ghế" },
    { jp: "ファイト", vn: "‘quyết chiến’, ‘cố lên’" },
    { jp: "マーク", vn: "kí hiệu" },
    { jp: "ボール", vn: "quả bóng" },
    { jp: "洗濯機（せんたくき）", vn: "máy giặt" },
    { jp: "ー機（ーき）", vn: "máy–" },
    { jp: "規則（きそく）", vn: "quy tắc, kỷ luật" },
    { jp: "使用禁止（しようきんし）", vn: "cấm sử dụng" },
    { jp: "立ち入り禁止（たちいりきんし）", vn: "cấm vào" },
    { jp: "入口（いりぐち）", vn: "cửa vào" },
    { jp: "出口（でぐち）", vn: "cửa ra" },
    { jp: "非常口（ひじょうぐち）", vn: "cửa thoát hiểm" },
    { jp: "無料（むりょう）", vn: "miễn phí" },
    { jp: "本日休業（ほんじつきゅうぎょう）", vn: "hôm nay đóng cửa, hôm nay nghỉ" },
    { jp: "営業中（えいぎょうちゅう）", vn: "đang mở cửa" },
    { jp: "使用中（しようちゅう）", vn: "đang sử dụng" },
    { jp: "ー中（ーちゅう）", vn: "đang–" },
    { jp: "どういうー", vn: "–gì, –thế nào" },
    { jp: "もう", vn: "không—nữa" },
    { jp: "あと", vn: "còn~" },
    { jp: "駐車違反（ちゅうしゃいはん）", vn: "đỗ xe trái phép" },
    { jp: "そりゃあ", vn: "thế thì, ồ" },
    { jp: "～以内（～いない）", vn: "~trong khoảng, ~trong vòng" },
    { jp: "警察（けいさつ）", vn: "cảnh sát" },
    { jp: "罰金（ばっきん）", vn: "tiền phạt" },
    { jp: "電報（でんぽう）", vn: "điện báo" },
    { jp: "人々（ひとびと）", vn: "nhiều người" },
    { jp: "急用（きゅうよう）", vn: "việc gấp" },
    { jp: "打ちます（うちます）（電報を）", vn: "gửi (điện báo)" },
    { jp: "電報代（でんぽうだい）", vn: "phí điện báo" },
    { jp: "できるだけ", vn: "cố gắng, trong khả năng có thể" },
    { jp: "短く（みじかく）", vn: "ngắn gọn" },
    { jp: "また", vn: "thêm nữa" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "危篤（キトク）", vn: "tình trạng hiểm nghèo" },
    { jp: "重い病気（おもいびょうき）", vn: "bệnh nặng" },
    { jp: "明日（あす）", vn: "ngày mai" },
    { jp: "留守（るす）", vn: "vắng nhà" },
    { jp: "留守番（るすばん）", vn: "trông nhà, giữ nhà" },
    { jp: "（お）祝い（おいわい）", vn: "việc mừng" },
    { jp: "なくなります", vn: "mất, chết" },
    { jp: "悲しい（かなしい）", vn: "buồn" },
    { jp: "利用します（りようします）", vn: "sử dụng, lợi dụng, tận dụng" }
  ],
  vocabList_u_34: [
    { jp: "（磨きます）みがきます", vn: "mài, đánh (răng)" },
    { jp: "（組み立てます）くみたてます", vn: "lắp ráp, lắp đặt" },
    { jp: "（折ります）おります", vn: "gấp, gập, bẻ gãy" },
    { jp: "（気が付きます）きがつきます", vn: "nhận thấy, phát hiện" },
    { jp: "（付けます）つけます", vn: "chấm" },
    { jp: "（見つかります）みつかります", vn: "được tìm thấy" },
    { jp: "（ネクタイを）します", vn: "đeo , thắt" },
    { jp: "（質問します）しつもんします", vn: "hỏi" },
    { jp: "（細い）ほそい", vn: "gầy, hẹp, thon" },
    { jp: "（太い）ふとい", vn: "béo, to" },
    { jp: "（盆踊り）ぼんおどり", vn: "múa trong hội bon" },
    { jp: "スポーツクラブ", vn: "câu lạc bộ thể thao" },
    { jp: "（家具）かぐ", vn: "gia cụ , đồ dùng nội thất" },
    { jp: "キー", vn: "chìa khóa" },
    { jp: "シートべルト", vn: "dây an toàn" },
    { jp: "（説明書）せつめいしょ", vn: "quyển hướng dẫn" },
    { jp: "（図）ず", vn: "sơ đồ, hình vẽ" },
    { jp: "（線）せん", vn: "đường" },
    { jp: "（矢印）やじるし", vn: "dấu mũi tên" },
    { jp: "（黒）くろ", vn: "màu đen" },
    { jp: "（白）しろ", vn: "màu trắng" },
    { jp: "（赤）あか", vn: "màu đỏ" },
    { jp: "（青）あお", vn: "màu xanh da trời" },
    { jp: "（紺）こん", vn: "màu xanh lam" },
    { jp: "（黄色）きいろ", vn: "màu vàng" },
    { jp: "（茶色）ちゃいろ", vn: "màu nâu" },
    { jp: "しょうゆ", vn: "xì dầu" },
    { jp: "ソース", vn: "nước chấm, nước xốt" },
    { jp: "ゆうべ", vn: "tối qua, đêm qua" },
    { jp: "さっき", vn: "vừa rồi, vừa lúc nãy" },
    { jp: "（茶道）さどう", vn: "trà đạo" },
    { jp: "（お茶をたてます）おちゃをたてます", vn: "pha trà" },
    { jp: "（先に）さきに", vn: "trước" },
    { jp: "（載せます）のせます", vn: "đặt lên" },
    { jp: "これでいいですか", vn: "Thế này được không/đã được chưa" },
    { jp: "（苦い）にがい", vn: "đắng" },
    { jp: "（親子どんぶり）おやこどんぶり", vn: "món oyako-don" },
    { jp: "（材料）ざいりょう", vn: "nguyên liệu" },
    { jp: "（－分）ーぶん", vn: "ーphần (biểu thị lượng)" },
    { jp: "（鶏肉）とりにく", vn: "thịt gà" },
    { jp: "ーグラム", vn: "gam" },
    { jp: "たまねぎ", vn: "hành củ" },
    { jp: "（４分の１）４ぶんの１", vn: "1/4 (một phần tư)" },
    { jp: "（調味料）ちょうみりょう", vn: "gia vị" },
    { jp: "なべ", vn: "nồi" },
    { jp: "（火）ひ", vn: "lửa" },
    { jp: "（火にかけます）ひにかけます", vn: "đun" },
    { jp: "（煮ます）にます", vn: "nấu" },
    { jp: "（煮えます）にえます", vn: "chín, được nấu" },
    { jp: "どんぶり", vn: "bát ô tô lớn" }
  ],
  vocabList_u_35: [
    { jp: "（咲きます）さきます", vn: "nở hoa" },
    { jp: "（変わります）かわります", vn: "thay đổi màu sắc" },
    { jp: "（困ります）こまります", vn: "khó khăn" },
    { jp: "（付けます）つけます", vn: "đánh dấu tròn" },
    { jp: "（治ります、直ります）なおります", vn: "khỏi bệnh" },
    { jp: "クリックします", vn: "click chuột" },
    { jp: "（入力します）にゅうりょくします", vn: "nhập vào" },
    { jp: "（正しい）ただしい", vn: "đúng" },
    { jp: "（向こう）むこう", vn: "phía đối diện" },
    { jp: "（島）しま", vn: "đảo" },
    { jp: "（港）みなと", vn: "cảng" },
    { jp: "（近所）きんじょ", vn: "hàng xóm" },
    { jp: "（屋上）おくじょう", vn: "tầng thượng" },
    { jp: "（海外）かいがい", vn: "nước ngoài" },
    { jp: "（山登り）やまのぼり", vn: "leo núi" },
    { jp: "（歴史）れきし", vn: "lịch sử" },
    { jp: "（機会）きかい", vn: "cơ hội" },
    { jp: "（許可）きょか", vn: "sự cho phép" },
    { jp: "（丸）まる", vn: "dấu tròn" },
    { jp: "（設備）せつび", vn: "thiết bị" },
    { jp: "レバー", vn: "cần gạt" },
    { jp: "キー", vn: "phím, chìa khóa" },
    { jp: "カーテン", vn: "rèm cửa" },
    { jp: "ひも", vn: "sợi dây" },
    { jp: "（炊飯器）すいはんき", vn: "nồi cơm điện" },
    { jp: "（葉）は", vn: "lá" },
    { jp: "（昔）むかし", vn: "ngày xưa" },
    { jp: "もっと", vn: "hơn nữa" },
    { jp: "（これで終わりましょう）これでおわりましょう", vn: "chúng ta dừng ở đây nhé" },
    { jp: "それなら", vn: "nếu thế thì, nếu vậy thì" },
    { jp: "（夜行バス）やこうばす", vn: "xe buýt đêm" },
    { jp: "さあ", vn: "ờ, à(dùng ở đầu câu nói khi không nắm rõ một việc gì đó" },
    { jp: "（旅行社）りょこうしゃ", vn: "công ty du lịch" },
    { jp: "（詳しい）くわしい", vn: "cụ thể, chi tiết" },
    { jp: "（スキー場）スキーじょう", vn: "khu trượt tuyết" },
    { jp: "（朱）しゅ", vn: "màu đỏ tươi" },
    { jp: "（交わります）まじわります", vn: "chơi với, quen với" },
    { jp: "ことわざ", vn: "thành ngữ" },
    { jp: "（関係）かんけい", vn: "quan hệ" },
    { jp: "（仲良くします）なかよくします", vn: "chơi thân với" },
    { jp: "（必要）ひつよう", vn: "cần thiết" },
  ],
  vocabList_u_36: [
    { jp: "届きます（とどきます）", vn: "được gửi đến, được chuyển đến" },
    { jp: "事故にあいます（じこにあいます）", vn: "gặp tai nạn" },
    { jp: "出ます（でます）", vn: "tham gia, tham dự" },
    { jp: "打ちます（うちます）", vn: "đánh" },
    { jp: "彫金します（ちょきんします）", vn: "tiết kiệm tiền, để dành tiền" },
    { jp: "太ります（ふとります）", vn: "béo lên, tăng cân" },
    { jp: "痩せます（やせます）", vn: "gầy đi, giảm cân" },
    { jp: "過ぎます（すぎます）", vn: "quá" },
    { jp: "慣れます（なれます）", vn: "làm quen, quen" },
    { jp: "固い（かたい）", vn: "cứng" },
    { jp: "軟らかい（やわらかい）", vn: "mềm" },
    { jp: "電子ー（でんしー）", vn: "– điện tử" },
    { jp: "携帯ー（けいたいー）", vn: "– cầm tay" },
    { jp: "工場（こうじょう）", vn: "nhà máy, phân xưởng" },
    { jp: "健康（けんこう）", vn: "sức khỏe" },
    { jp: "剣道（けんどう）", vn: "kiếm đạo" },
    { jp: "毎週（まいしゅう）", vn: "hàng tuần" },
    { jp: "毎月（まいつき）", vn: "hàng tháng" },
    { jp: "毎年（まいとし）", vn: "hàng năm" },
    { jp: "やっと", vn: "cuối cùng thì" },
    { jp: "かなり", vn: "khá, tương đối" },
    { jp: "必ず（かならず）", vn: "nhất định" },
    { jp: "絶対に（ぜったいに）", vn: "tuyệt đối" },
    { jp: "上手に（じょうずに）", vn: "giỏi, khéo" },
    { jp: "できるだけ", vn: "cố gắng" },
    { jp: "このごろ", vn: "gần đây, dạo này" },
    { jp: "そのほうがー", vn: "cái đó – hơn" },
    { jp: "お客様（おきゃくさま）", vn: "khách hàng" },
    { jp: "特別（な）（とくべつな）", vn: "đặc biệt" },
    { jp: "していらっしゃいます", vn: "đang làm (tôn kính ngữ của しています)" },
    { jp: "水泳（すいえい）", vn: "môn bơi lội" },
    { jp: "～とか、～とか", vn: "như là...và～và" },
    { jp: "タンゴ", vn: "tango" },
    { jp: "チャレンジします", vn: "thách thức, thử thách" },
    { jp: "気持ち（きもち）", vn: "cảm giác, tâm trạng, tinh thần" },
    { jp: "乗り物（のりもの）", vn: "phương tiện đi lại" },
    { jp: "歴史（れきし）", vn: "lịch sử" },
    { jp: "世紀（ーせいき）", vn: "thế kỉ –" },
    { jp: "遠く（とおく）", vn: "xa, ở xa" },
    { jp: "汽車（きしゃ）", vn: "tàu hỏa chạy bằng hơi nước" },
    { jp: "汽船（きせん）", vn: "thuyền chạy bằng hơi nước" },
    { jp: "大勢の人（おおぜいのひと）", vn: "nhiều (người)" },
    { jp: "運びます（はこびます）", vn: "vận chuyển" },
    { jp: "安全（な）（あんぜんな）", vn: "an toàn" },
    { jp: "飛びます（とびます）", vn: "bay" },
    { jp: "宇宙（うちゅう）", vn: "vũ trụ" },
    { jp: "地球（ちきゅう）", vn: "trái đất" }
  ],
  vocabList_u_37: [
    { jp: "褒めます（ほめます）", vn: "khen" },
    { jp: "叱ります（しかります）", vn: "mắng" },
    { jp: "誘います（さそいます）", vn: "mời, rủ rê" },
    { jp: "起こします（おこします）", vn: "đánh thức" },
    { jp: "招待します（しょうたいします）", vn: "mời" },
    { jp: "頼みます（たのみます）", vn: "nhờ" },
    { jp: "注意します（ちゅういします）", vn: "chú ý, nhắc nhở" },
    { jp: "取ります（とります）", vn: "ăn trộm, lấy cắp" },
    { jp: "踏みます（ふみます）", vn: "giẫm, giẫm lên" },
    { jp: "壊します（こわします）", vn: "phá, làm hỏng" },
    { jp: "汚します（よごします）", vn: "làm bẩn" },
    { jp: "行います（おこないます）", vn: "thực hiện, tiến hành" },
    { jp: "輸出します（ゆしゅつします）", vn: "xuất khẩu" },
    { jp: "輸入します（ゆにゅうします）", vn: "nhập khẩu" },
    { jp: "翻訳します（ほんやくします）", vn: "dịch (sách, tài liệu)" },
    { jp: "発明します（はつめいします）", vn: "phát minh" },
    { jp: "発見します（はっけんします）", vn: "phát kiến, tìm ra" },
    { jp: "設計します（せっけいします）", vn: "thiết kế" },
    { jp: "米（こめ）", vn: "gạo" },
    { jp: "麦（むぎ）", vn: "lúa mạch" },
    { jp: "石油（せきゆ）", vn: "dầu mỏ" },
    { jp: "原料（げんりょう）", vn: "nguyên liệu" },
    { jp: "デート", vn: "cuộc hẹn hò" },
    { jp: "泥棒（どろぼう）", vn: "kẻ trộm" },
    { jp: "警官（けいかん）", vn: "cảnh sát" },
    { jp: "建築家（けんちくか）", vn: "kiến trúc sư" },
    { jp: "科学者（かがくしゃ）", vn: "nhà khoa học" },
    { jp: "漫画（まんが）", vn: "truyện tranh" },
    { jp: "世界中（せかいじゅう）", vn: "khắp thế giới, toàn thế giới" },
    { jp: "ー中（ーじゅう）", vn: "khắp –" },
    { jp: "ーによって", vn: "do –" },
    { jp: "よかったですね", vn: "may nhỉ" },
    { jp: "埋め立てます（うめたてます）", vn: "lấp" },
    { jp: "技術（ぎじゅつ）", vn: "kỹ thuật" },
    { jp: "土地（とち）", vn: "đất, diện tích đất" },
    { jp: "騒音（そうおん）", vn: "tiếng ồn" },
    { jp: "利用します（りようします）", vn: "sử dụng" },
    { jp: "アクセス", vn: "nối, giao thông đi đến" },
    { jp: "ドミニカ", vn: "Dominica (tên một quốc gia ở Trung Mỹ)" },
    { jp: "世紀（ーせいき）", vn: "thế kỉ –" },
    { jp: "豪華（な）（ごうかな）", vn: "hào hoa, sang trọng" },
    { jp: "彫刻（ちょうこく）", vn: "điêu khắc" },
    { jp: "眠ります（ねむります）", vn: "ngủ" },
    { jp: "彫ります（ほります）", vn: "khắc" },
    { jp: "仲間（なかま）", vn: "bạn bè, đồng nghiệp" },
    { jp: "そのあと", vn: "sau đó" },
    { jp: "一生懸命（いっしょうけんめい）", vn: "cố gắng hết sức" },
    { jp: "ねずみ", vn: "chuột" },
    { jp: "一匹もいません（いっぴきもいません）", vn: "không có con nào cả" }
  ],
  vocabList_u_38: [
    { jp: "育てます（そだてます）", vn: "nuôi, trồng" },
    { jp: "運びます（はこびます）", vn: "chở, vận chuyển" },
    { jp: "亡くなります（なくなります）", vn: "mất, qua đời" },
    { jp: "入院します（にゅういんします）", vn: "nhập viện" },
    { jp: "退院します（たいいんします）", vn: "xuất viện" },
    { jp: "入れます（いれます）", vn: "bật" },
    { jp: "切ります（きります）", vn: "tắt" },
    { jp: "掛けます（かけます）", vn: "khóa" },
    { jp: "気持ちがいい（きもちがいい）", vn: "dễ chịu, thư giãn" },
    { jp: "気持ちが悪い（きもちがわるい）", vn: "khó chịu" },
    { jp: "大きな（おおきな）", vn: "to, lớn" },
    { jp: "小さな（ちいさな）", vn: "nhỏ, bé" },
    { jp: "赤ちゃん（あかちゃん）", vn: "em bé" },
    { jp: "小学校（しょうがっこう）", vn: "trường tiểu học" },
    { jp: "中学校（ちゅうがっこう）", vn: "trường trung học cơ sở" },
    { jp: "駅前（えきまえ）", vn: "khu vực trước nhà ga" },
    { jp: "海岸（かいがん）", vn: "bờ biển" },
    { jp: "うそ", vn: "nói dối, lời nói dối" },
    { jp: "書類（しょるい）", vn: "giấy tờ, tài liệu" },
    { jp: "電源（でんげん）", vn: "nguồn điện, công tắc điện" },
    { jp: "〜製（〜せい）", vn: "sản xuất tại –" },
    { jp: "あ、いけない", vn: "Ôi, hỏng mất rồi / Ôi, trời ơi" },
    { jp: "お先に（おさきに）", vn: "Tôi xin phép về trước" },
    { jp: "回覧（かいらん）", vn: "tập thông báo" },
    { jp: "研究者室（けんきゅうしつ）", vn: "phòng nghiên cứu" },
    { jp: "きちんと", vn: "nghiêm chỉnh, hẳn hoi, đứng đắn" },
    { jp: "整理します（せいりします）", vn: "sắp xếp" },
    { jp: "はんこ", vn: "con dấu, dấu" },
    { jp: "押します（おします）", vn: "đóng (dấu)" },
    { jp: "双子（ふたご）", vn: "cặp sinh đôi" },
    { jp: "姉妹（しまい）", vn: "chị em" },
    { jp: "5年生（ごねんせい）", vn: "học sinh năm thứ 5" },
    { jp: "似ています（にています）", vn: "giống" },
    { jp: "性格（せいかく）", vn: "tính cách" },
    { jp: "おとなしい", vn: "hiền lành, trầm" },
    { jp: "世話をします（せわをします）", vn: "chăm sóc, giúp đỡ" },
    { jp: "時間がたちます（じかんがたちます）", vn: "thời gian trôi đi" },
    { jp: "だいすき", vn: "rất thích" },
    { jp: "クラス", vn: "lớp học, lớp" },
    { jp: "けんかします", vn: "cãi nhau" },
    { jp: "不思議（ふしぎ）", vn: "bí ẩn, kỳ thú, khó hiểu" }
  ],
  vocabList_u_39: [
    { jp: "答えます（こたえます）", vn: "trả lời" },
    { jp: "倒れます（たおれます）", vn: "đổ" },
    { jp: "焼けます（やけます）", vn: "cháy" },
    { jp: "焼けます（パン/肉が～）（やけます）", vn: "nướng (bánh mì / thịt)" },
    { jp: "通ります（とおります）", vn: "đi qua" },
    { jp: "死にます（しにます）", vn: "chết" },
    { jp: "びっくりします", vn: "ngạc nhiên, giật mình" },
    { jp: "がっかりします", vn: "thất vọng" },
    { jp: "安心します（あんしんします）", vn: "yên tâm" },
    { jp: "遅刻します（ちこくします）", vn: "đến chậm , đến muộn" },
    { jp: "早退します（そうたいします）", vn: "về sớm, ra sớm" },
    { jp: "けんかします", vn: "cãi nhau" },
    { jp: "離婚します（りこんします）", vn: "ly dị, ly hôn" },
    { jp: "複雑（ふくざつ）", vn: "phức tạp" },
    { jp: "邪魔（じゃま）", vn: "cản trở, chiếm diện tích" },
    { jp: "汚い（きたない）", vn: "bẩn" },
    { jp: "うれしい", vn: "vui mừng" },
    { jp: "悲しい（かなしい）", vn: "buồn, đau thương" },
    { jp: "恥ずかしい（はずかしい）", vn: "xấu hổ, thẹn, hổ thẹn" },
    { jp: "地震（じしん）", vn: "động đất" },
    { jp: "台風（たいふう）", vn: "bão" },
    { jp: "火事（かじ）", vn: "hỏa hoạn" },
    { jp: "事故（じこ）", vn: "tai nạn, sự cố" },
    { jp: "見合い（みあい）", vn: "xem mặt, làm mối" },
    { jp: "電話代（でんわだい）", vn: "tiền điện thoại, phí điện thoại" },
    { jp: "ー代（ーだい）", vn: "– tiền (phí –)" },
    { jp: "フロント", vn: "bộ phận tiếp tân" },
    { jp: "ー号室（ーごうしつ）", vn: "phòng số–" },
    { jp: "汗（あせ）", vn: "mồ hôi" },
    { jp: "タオル", vn: "khăn lau, khăn tắm" },
    { jp: "せっけん", vn: "xà phòng" },
    { jp: "大勢（おおぜい）", vn: "nhiều người" },
    { jp: "お疲れさまでした（おつかれさまでした）", vn: "Chắc anh/chị đã mệt vì làm việc" },
    { jp: "伺います（うかがいます）", vn: "tôi đến thăm (khiêm nhường ngữ)" },
    { jp: "途中で（とちゅうで）", vn: "giữa đường, giữa chừng" },
    { jp: "トラック", vn: "xe tải" },
    { jp: "ぶつかります", vn: "đâm , va chạm" },
    { jp: "並びます（ならびます）", vn: "xếp hàng" },
    { jp: "大人（おとな）", vn: "người lớn" },
    { jp: "洋服（ようふく）", vn: "quần áo kiểu tây âu" },
    { jp: "西洋化します（せいようかします）", vn: "Tây Âu hóa" },
    { jp: "会います（あいます）", vn: "vừa, hợp" },
    { jp: "今では（いまでは）", vn: "bây giờ (thì)" },
    { jp: "成人式（せいじんしき）", vn: "lễ trưởng thành, lễ thành nhân" }
  ],
  vocabList_u_40: [
    { jp: "測ります（はかります）", vn: "đo (độ dài, cân nặng...)" },
    { jp: "確かめます（たしかめます）", vn: "xác nhận, làm cho rõ ràng" },
    { jp: "合います（あいます）", vn: "vừa, hợp (cỡ)" },
    { jp: "出発します（しゅっぱつします）", vn: "xuất phát" },
    { jp: "到着します（とうちゃくします）", vn: "đến nơi" },
    { jp: "酔います（よいます）", vn: "say (rượu, xe...)" },
    { jp: "うまくいきます", vn: "thuận lợi, suôn sẻ" },
    { jp: "問題が出ます（もんだいがでます）", vn: "có câu hỏi (trong đề thi)" },
    { jp: "相談します（そうだんします）", vn: "trao đổi, bàn bạc" },
    { jp: "必要な（ひつような）", vn: "cần thiết" },
    { jp: "新年会（しんねんかい）", vn: "tiệc mừng năm mới" },
    { jp: "忘年会（ぼうねんかい）", vn: "tiệc cuối năm" },
    { jp: "二次会（にじかい）", vn: "tăng hai" },
    { jp: "大会（たいかい）", vn: "đại hội" },
    { jp: "コンテスト", vn: "cuộc thi" },
    { jp: "表（おもて）", vn: "mặt trước" },
    { jp: "裏（うら）", vn: "mặt sau" },
    { jp: "返事（へんじ）", vn: "hồi âm, trả lời" },
    { jp: "間違い（まちがい）", vn: "lỗi, sai" },
    { jp: "キズ", vn: "vết xước, vết thương" },
    { jp: "ズボン", vn: "quần" },
    { jp: "長さ（ながさ）", vn: "chiều dài" },
    { jp: "重さ（おもさ）", vn: "trọng lượng" },
    { jp: "高さ（たかさ）", vn: "chiều cao" },
    { jp: "大きさ（おおきさ）", vn: "độ lớn, kích thước" },
    { jp: "～便（～びん）", vn: "chuyến (bay) ～" },
    { jp: "～号（～ごう）", vn: "số hiệu ～" },
    { jp: "～本（～ほん・ぽん・ぼん）", vn: "đơn vị đếm vật dài" },
    { jp: "～杯（～はい・ぱい・ばい）", vn: "đơn vị đếm chén, ly" },
    { jp: "～キロ", vn: "～ kg, ～ km" },
    { jp: "～グラム", vn: "～ gam" },
    { jp: "～センチ", vn: "～ cm" },
    { jp: "～ミリ", vn: "～ mm" },
    { jp: "～以上（～いじょう）", vn: "từ ～ trở lên" },
    { jp: "～以下（～いか）", vn: "dưới ～" },
    { jp: "どうでしょうか", vn: "thế nào (lịch sự của どうですか)" },
    { jp: "テスト", vn: "bài kiểm tra" },
    { jp: "成績（せいせき）", vn: "thành tích, kết quả" },
    { jp: "様子（ようす）", vn: "tình hình, trạng thái" },
    { jp: "事件（じけん）", vn: "vụ việc, sự cố" },
    { jp: "オートバイ", vn: "xe máy" },
    { jp: "積みます（つみます）", vn: "chất lên, xếp hàng lên" },
    { jp: "運転手（うんてんしゅ）", vn: "tài xế" },
    { jp: "離れた（はなれた）", vn: "xa, cách xa" },
    { jp: "急に（きゅうに）", vn: "đột nhiên, gấp" },
    { jp: "動かします（うごかします）", vn: "di chuyển, vận hành" },
    { jp: "犯人（はんにん）", vn: "thủ phạm" },
    { jp: "手に入れます（てにいれます）", vn: "có được, lấy được" },
    { jp: "今でも（いまでも）", vn: "ngay cả bây giờ" },
    { jp: "噂します（うわさします）", vn: "đồn đại, bàn tán" }
  ],
  vocabList_u_41: [
    { jp: "いただきます", vn: "nhận (khiêm nhường ngữ của もらいます)" },
    { jp: "下さいます（くださいます）", vn: "cho, tặng (tôi) [tôn kính ngữ của くれます]" },
    { jp: "やります", vn: "cho, tặng (người dưới hoặc động vật, thực vật)" },
    { jp: "上げます（あげます）", vn: "tăng, nâng lên" },
    { jp: "下げます（さげます）", vn: "giảm xuống" },
    { jp: "親切にします（しんせつにします）", vn: "đối xử tử tế, thân thiện" },
    { jp: "可愛い（かわいい）", vn: "dễ thương, đáng yêu" },
    { jp: "珍しい（めずらしい）", vn: "hiếm, hiếm có" },
    { jp: "お祝い（おいわい）", vn: "mừng, quà mừng" },
    { jp: "お年玉（おとしだま）", vn: "tiền mừng tuổi" },
    { jp: "お見舞い（おみまい）", vn: "thăm người bệnh, quà thăm hỏi" },
    { jp: "情報（じょうほう）", vn: "thông tin" },
    { jp: "発音（はつおん）", vn: "phát âm" },
    { jp: "猿（さる）", vn: "con khỉ" },
    { jp: "餌（えさ）", vn: "mồi, thức ăn cho động vật" },
    { jp: "おもちゃ", vn: "đồ chơi" },
    { jp: "絵本（えほん）", vn: "sách tranh" },
    { jp: "絵はがき（えはがき）", vn: "bưu thiếp tranh" },
    { jp: "ドライバー", vn: "tuốc-nơ-vít" },
    { jp: "ハンカチ", vn: "khăn tay" },
    { jp: "靴下（くつした）", vn: "tất, vớ" },
    { jp: "手袋（てぶくろ）", vn: "găng tay" },
    { jp: "指輪（ゆびわ）", vn: "nhẫn" },
    { jp: "バッグ", vn: "túi xách" },
    { jp: "祖父（そふ）", vn: "ông (của mình)" },
    { jp: "祖母（そぼ）", vn: "bà (của mình)" },
    { jp: "孫（まご）", vn: "cháu (của mình)" },
    { jp: "お孫さん（おまごさん）", vn: "cháu (của người khác)" },
    { jp: "叔父 / 伯父（おじ）", vn: "chú, bác, cậu (của mình)" },
    { jp: "叔母 / 伯母（おば）", vn: "cô, dì, bác (của mình)" },
    { jp: "おじさん", vn: "chú, bác, cậu (của người khác)" },
    { jp: "おばさん", vn: "cô, dì, bác (của người khác)" },
    { jp: "この間（このあいだ）", vn: "vừa rồi, hôm nọ" },
    { jp: "一言（ひとこと）", vn: "một vài lời, một câu" },
    { jp: "二人（ふたり）", vn: "hai người" },
    { jp: "興味（きょうみ）", vn: "sở thích, quan tâm" },
    { jp: "縁起がいい（えんぎがいい）", vn: "may mắn, tốt lành" },
    { jp: "それに", vn: "thêm nữa là, hơn nữa là" },
    { jp: "預かります（あずかります）", vn: "giữ, trông nom, chăm sóc" },
    { jp: "助かります（たすかります）", vn: "được giúp đỡ, may quá" },
    { jp: "昔話（むかしばなし）", vn: "truyện cổ tích" },
    { jp: "ある～", vn: "có một～ (dùng để mở đầu truyện)" },
    { jp: "子供たち（こどもたち）", vn: "trẻ em, bọn trẻ" },
    { jp: "いじめます", vn: "bắt nạt" },
    { jp: "亀（かめ）", vn: "con rùa" },
    { jp: "助けます（たすけます）", vn: "giúp, cứu giúp, cứu sống" },
    { jp: "お姫様（おひめさま）", vn: "công chúa" },
    { jp: "暮らします（くらします）", vn: "sống, sinh hoạt" },
    { jp: "陸（りく）", vn: "lục địa, đất liền" },
    { jp: "煙（けむり）", vn: "khói" },
    { jp: "真っ白な（まっしろな）", vn: "trắng toát, trắng xóa" },
    { jp: "中身（なかみ）", vn: "bên trong, nội dung" },
    { jp: "文法（ぶんぽう）", vn: "ngữ pháp" }
  ],
  vocabList_u_42: [
    { jp: "包みます（つつみます）", vn: "bọc, gói" },
    { jp: "沸かします（わかします）", vn: "đun sôi" },
    { jp: "混ぜます（まぜます）", vn: "trộn, khuấy" },
    { jp: "計算します（けいさんします）", vn: "tính toán" },
    { jp: "並びます（ならびます）", vn: "xếp hàng" },
    { jp: "丈夫（じょうぶ）", vn: "bền, chắc" },
    { jp: "音楽家（おんがくか）", vn: "nhạc sĩ" },
    { jp: "子どもたち（こどもたち）", vn: "trẻ em" },
    { jp: "自然（しぜん）", vn: "tự nhiên" },
    { jp: "教育（きょういく）", vn: "giáo dục" },
    { jp: "文化（ぶんか）", vn: "văn hoá" },
    { jp: "社会（しゃかい）", vn: "xã hội" },
    { jp: "政治（せいじ）", vn: "chính trị" },
    { jp: "法律（ほうりつ）", vn: "pháp luật" },
    { jp: "戦争（せんそう）", vn: "chiến tranh" },
    { jp: "平和（へいわ）", vn: "hòa bình" },
    { jp: "目的（もくてき）", vn: "mục đích" },
    { jp: "論文（ろんぶん）", vn: "luận văn" },
    { jp: "楽しみ（たのしみ）", vn: "niềm vui, điều mong đợi" },
    { jp: "ミキサー", vn: "máy xay (sinh tố, thực phẩm)" },
    { jp: "やかん", vn: "ấm đun nước" },
    { jp: "ふた", vn: "nắp, vung" },
    { jp: "栓抜き（せんぬき）", vn: "cái mở nắp chai" },
    { jp: "缶切り（かんきり）", vn: "cái mở hộp" },
    { jp: "缶（かん）", vn: "lon, hộp kim loại" },
    { jp: "のし袋（のしぶくろ）", vn: "phong bì (dùng bỏ tiền mừng)" },
    { jp: "ふろしき", vn: "khăn vuông gói đồ" },
    { jp: "体温計（たいおんけい）", vn: "nhiệt kế" },
    { jp: "そろばん", vn: "bái bàn tính" },
    { jp: "材料（ざいりょう）", vn: "nguyên liệu, vật liệu" },
    { jp: "ある～", vn: "một-nọ" },
    { jp: "なぜ", vn: "tại sao" },
    { jp: "一生懸命（いっしょうけんめい）", vn: "chăm chỉ, cố gắng hết sức" },
    { jp: "どのくらい", vn: "bao nhiêu (lượng, thời gian)" },
    { jp: "あと", vn: "còn lại" },
    { jp: "カップめん", vn: "mì ăn liền ly" },
    { jp: "インスタントラーメン", vn: "mì ăn liền" },
    { jp: "データ", vn: "dữ liệu" },
    { jp: "世界初（せかいはつ）", vn: "đầu tiên trên thế giới" },
    { jp: "〜によって", vn: "do ~" },
    { jp: "広めます（ひろめます）", vn: "mở rộng, phổ cập" },
    { jp: "割ります（わります）", vn: "làm vỡ, chia ra" },
    { jp: "市場調査（しじょうちょうさ）", vn: "điều tra thị trường" },
    { jp: "どんぶり", vn: "bát tô lớn" },
    { jp: "めん", vn: "mì sợi" },
    { jp: "ローン", vn: "khoản vay" },
    { jp: "半分（はんぶん）", vn: "một nửa" },
    { jp: "出ます「ボーナスが」（でます）", vn: "có thưởng" },
    { jp: "注ぎます（そそぎます）", vn: "rót" }
  ],
  vocabList_u_43: [
    { jp: "増えます（ふえます）", vn: "tăng lên (xuất khẩu, dân số…)" },
    { jp: "減ります（へります）", vn: "giảm xuống (xuất khẩu, dân số…)" },
    { jp: "上がります（あがります）", vn: "tăng lên (giá cả…)" },
    { jp: "下がります（さがります）", vn: "giảm xuống (giá cả…)" },
    { jp: "切れます（きれます）", vn: "đứt (sợi dây…)" },
    { jp: "とれます", vn: "tuột ra, rơi ra (nút áo…)" },
    { jp: "落ちます（おちます）", vn: "rơi (hành lý…)" },
    { jp: "なくなります", vn: "hết, mất (xăng…)" },
    { jp: "変［な］（へん［な］）", vn: "lạ, kỳ quặc" },
    { jp: "幸せ（しあわせ）", vn: "hạnh phúc" },
    { jp: "楽（らく）", vn: "nhàn nhã" },
    { jp: "ガソリン", vn: "xăng" },
    { jp: "パンフレット", vn: "tờ rơi quảng cáo" },
    { jp: "今にも（いまにも）", vn: "bất kì lúc nào (diễn tả trạng thái có thể thay đổi bất kì lúc nào)" },
    { jp: "良さそうです（よさそうです）", vn: "có vẻ tốt" },
    { jp: "わあ", vn: "ôi" },
    { jp: "ばら", vn: "hoa hồng" },
    { jp: "理由（りゆう）", vn: "lý do" },
    { jp: "謝ります（あやまります）", vn: "xin lỗi" },
    { jp: "知合います（しりあいます）", vn: "quen biết" },
    { jp: "うまい", vn: "ngon, giỏi (thường dùng văn nói)" },
    { jp: "まずい", vn: "dở (món ăn…)" },
    { jp: "つまらない", vn: "chán, không thú vị" },
    { jp: "やさしい", vn: "hiền lành (người)" },
    { jp: "今にも（いまにも）", vn: "bất kỳ lúc nào (ngay bây giờ)" },
    { jp: "ドライブ", vn: "lái xe đi chơi" },
    { jp: "原因（げんいん）", vn: "nguyên nhân" },
    { jp: "センス", vn: "có gu, có khiếu (センスがある)" },
    { jp: "例えば（たとえば）", vn: "ví dụ như…" },
    { jp: "洋服（ようふく）", vn: "quần áo kiểu Tây" },
    { jp: "合います（あいます）", vn: "vừa, hợp (vừa cỡ, hợp với…)" }
  ],
  vocabList_u_44: [
    { jp: "泣きます（なきます）", vn: "khóc" },
    { jp: "笑います（わらいます）", vn: "cười" },
    { jp: "眠ります（ねむります）", vn: "ngủ" },
    { jp: "乾きます（かわきます）", vn: "khô" },
    { jp: "ぬれます", vn: "ướt" },
    { jp: "滑ります（すべります）", vn: "trượt" },
    { jp: "起きます（おきます）", vn: "xảy ra (tai nạn…)" },
    { jp: "調節します（ちょうせつします）", vn: "điều chỉnh" },
    { jp: "安全（あんぜん）", vn: "an toàn" },
    { jp: "危険（きけん）", vn: "nguy hiểm" },
    { jp: "丁寧（ていねい）", vn: "lịch sự, cẩn thận" },
    { jp: "細かい（こまかい）", vn: "chi tiết, nhỏ" },
    { jp: "濃い（こい）", vn: "đậm (vị, màu…)" },
    { jp: "薄い（うすい）", vn: "nhạt (vị, màu…)" },
    { jp: "太い（ふとい）", vn: "dày, béo, to (đường kính…)" },
    { jp: "細い（ほそい）", vn: "mỏng, thon, nhỏ" },
    { jp: "和食（わしょく）", vn: "món ăn Nhật" },
    { jp: "洋食（ようしょく）", vn: "món ăn kiểu Tây" },
    { jp: "おかず", vn: "món ăn kèm" },
    { jp: "量（りょう）", vn: "lượng, số lượng" },
    { jp: "倍（ばい）", vn: "gấp đôi, lần" },
    { jp: "半分（はんぶん）", vn: "một nửa" },
    { jp: "シングル", vn: "phòng đơn (khách sạn)" },
    { jp: "ツイン", vn: "phòng đôi (khách sạn)" },
    { jp: "洗濯物（せんたくもの）", vn: "quần áo giặt" },
    { jp: "どうなさいますか", vn: "quý khách muốn làm thế nào?" },
    { jp: "カット", vn: "cắt tóc" },
    { jp: "シャンプー", vn: "dầu gội (～をします：gội đầu)" },
    { jp: "ショート", vn: "tóc ngắn" },
    { jp: "どういうふうになさいますか", vn: "quý khách muốn làm kiểu như thế nào?" },
    { jp: "これでよろしいでしょうか", vn: "như thế này được không ạ?" },
    { jp: "［どうも］お疲れさまでした（おつかれさまでした）", vn: "[cám ơn] đã vất vả rồi" },
    { jp: "嫌がります（いやがります）", vn: "ghét, không thích" },
    { jp: "表現（ひょうげん）", vn: "biểu hiện, cách nói" },
    { jp: "別れます（わかれます）", vn: "chia tay, chia ra" },
    { jp: "縁起が悪い（えんぎがわるい）", vn: "xui, không may" },
    { jp: "～みたいにしてください", vn: "như thê này được chưa" },
    { jp: "空気（くうき）", vn: "không khí" },
    { jp: "涙（なみだ）", vn: "nước mắt" },
    { jp: "また", vn: "hơn nữa" },
    { jp: "うまく", vn: "tốt, giỏi" },
    { jp: "順序（じゅんじょ）", vn: "trình tự" },
    { jp: "安心（あんしん）", vn: "yên tâm" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "これら", vn: "những từ này" },
  ],
  vocabList_u_45: [
    { jp: "信じます（しんじます）", vn: "tin tưởng" },
    { jp: "キャンセルします", vn: "hủy, hủy bỏ" },
    { jp: "知らせます（しらせます）", vn: "thông báo" },
    { jp: "保証書（ほしょうしょ）", vn: "giấy bảo hành" },
    { jp: "領収書（りょうしゅうしょ）", vn: "hóa đơn" },
    { jp: "中止（ちゅうし）", vn: "hoãn, ngừng" },
    { jp: "点（てん）", vn: "điểm, điểm số" },
    { jp: "梅（うめ）", vn: "hoa nở" },
    { jp: "急に（きゅうに）", vn: "gấp, đột nhiên" },
    { jp: "無理に（むりに）", vn: "cố, gắng sức" },
    { jp: "楽しみにしています（たのしみにしています）", vn: "mong đợi, mong chờ" },
    { jp: "以上です（いじょうです）", vn: "xin hết, tôi xin nói hết" },
    { jp: "係員（かかりいん）", vn: "nhân viên phụ trách" },
    { jp: "コース", vn: "khóa học, đường chạy (marathon…)" },
    { jp: "スタート", vn: "xuất phát" },
    { jp: "ー位（－い）", vn: "thứ-" },
    { jp: "優勝します（ゆうしょうします）", vn: "vô địch, chiến thắng" },
    { jp: "悩み（なやみ）", vn: "nỗi khổ tâm, trăn trở" },
    { jp: "目覚まし時計（めざましとけい）", vn: "đồng hồ báo thức" },
    { jp: "目が覚めます（めがさめます）", vn: "tỉnh giấc, thức giấc" },
    { jp: "回答（かいとう）（～します）", vn: "câu trả lời (trả lời)" },
    { jp: "鳴ります（なります）", vn: "reo, kêu (chuông…)" },
    { jp: "セットします", vn: "cài đặt, chỉnh (giờ…)" },
    { jp: "それでも", vn: "mặc dù vậy, dù thế đi nữa" }
  ],
  vocabList_u_46: [
    { jp: "届きます（とどきます）", vn: "được gửi đến, được chuyển đến" },
    { jp: "渡します（わたします）", vn: "đưa cho, giao cho" },
    { jp: "帰ってきます（かえってきます）", vn: "về, trở lại" },
    { jp: "留守（るす）", vn: "vắng nhà" },
    { jp: "宅配便（たくはいびん）", vn: "dịch vụ chuyển đồ đến nhà" },
    { jp: "原因（げんいん）", vn: "nguyên nhân" },
    { jp: "～のところ", vn: "quanh-, xung quanh-" },
    { jp: "ガスサービスセンター", vn: "trung tâm dịch vụ ga" },
    { jp: "ガスレンジ", vn: "bếp ga" },
    { jp: "申し訳ございません（もうしわけございません）", vn: "xin lỗi" },
    { jp: "付いています（ついています）", vn: "may mắn" },
    { jp: "床（ゆか）", vn: "sàn nhà" },
    { jp: "転びます（ころびます）", vn: "ngã" },
    { jp: "ベル", vn: "chuông cửa" },
    { jp: "出ます（バスがでます）", vn: "xuất phát, chạy (xe buýt)" },
    { jp: "入学します（にゅうがくします）", vn: "nhập học (trường đại học…)" },
    { jp: "卒業します（そつぎょうします）", vn: "tốt nghiệp (trường đại học…)" },
    { jp: "焼きます（やきます）", vn: "nướng, rán" },
    { jp: "焼けます（やけます）", vn: "được nướng chín, được rán chín" },
    { jp: "パンが焼けます（やけます）", vn: "bánh mì được nướng chín" },
    { jp: "肉が焼けます（やけます）", vn: "thịt được nướng chín" },
    { jp: "たった今（たったいま）", vn: "vừa mới (nhấn mạnh hành động vừa kết thúc)" },
    { jp: "今いいですか（いまいいですか）", vn: "bây giờ tôi làm phiền được không?" },
    { jp: "具合（ぐあい）", vn: "tình trạng, tình hình, tình trạng sức khỏe" },
    { jp: "どちら様でしょうか（どちらさまでしょうか）", vn: "ai đấy ạ?" },
    { jp: "向かいます（むかいます）", vn: "hướng về, trên đường tới" },
    { jp: "お待たせしました（おまたせしました）", vn: "xin lỗi đã để bạn đợi" },
    { jp: "途中で（とちゅうで）", vn: "giữa đường, giữa chừng" },
    { jp: "宝くじ（たからくじ）", vn: "xổ số" },
    { jp: "当たります（あたります）", vn: "trúng (xổ số…)" },
    { jp: "急に（きゅうに）", vn: "đột nhiên, gấp" },
    { jp: "今朝（けさ）", vn: "sáng nay" },
    { jp: "慌てて（あわてて）", vn: "vội vàng, hấp tấp" },
    { jp: "順番に（じゅんばんに）", vn: "theo thứ tự" },
    { jp: "出来事（できごと）", vn: "sự việc, sự kiện" }
  ],
  vocabList_u_47: [
    { jp: "吹きます（ふきます）", vn: "thổi" },
    { jp: "燃えます（燃えます）", vn: "cháy(rác)" },
    { jp: "亡くなります", vn: "qua đời (từ nói tránh しにます）" },
    { jp: "厳しい（きびしい）", vn: "nghiêm khắc" },
    { jp: "怖い（こわい）", vn: "sợ, khiếp" },
    { jp: "データ", vn: "dữ liệu" },
    { jp: "におい", vn: "mùi" },
    { jp: "大統領（だいとうりょう）", vn: "tổng thống" },
    { jp: "恋人（こいびと）", vn: "người yêu" },
    { jp: "相手（あいて）", vn: "đối phương, đối tác, người kia, nửa còn lại" },
    { jp: "知合います（しりあいます）", vn: "quen biết" },
    { jp: "化粧（けしょう）", vn: "trang điểm" },
    { jp: "世話をします（せわをします）", vn: "chăm sóc" },
    { jp: "関係（かんけい）", vn: "quan hệ" },
    { jp: "集まります（あつまります）", vn: "tập trung, tập hợp" },
    { jp: "別れます（わかれます）", vn: "chia, chia nhỏ, chia tay" },
    { jp: "長生きします（ながいきします）", vn: "sống lâu, trường thọ" },
    { jp: "声がします（こえがします）", vn: "có tiếng (người)" },
    { jp: "音がします（おとがします）", vn: "có tiếng (động vật, vật)" },
    { jp: "味がします（あじがします）", vn: "có vị" },
    { jp: "においがします", vn: "có mùi" },
    { jp: "ひどい", vn: "kinh khủng, khủng khiếp, tồi tệ" },
    { jp: "実験（じっけん）", vn: "thí nghiệm" },
    { jp: "人口（じんこう）", vn: "dân số" },
    { jp: "科学（かがく）", vn: "khoa học" },
    { jp: "医学（いがく）", vn: "y học" },
    { jp: "文学（ぶんがく）", vn: "văn học" },
    { jp: "パトカー", vn: "xe tuần tra cảnh sát" },
    { jp: "救急車（きゅうきゅうしゃ）", vn: "xe cấp cứu" },
    { jp: "賛成（さんせい）", vn: "tán thành" },
    { jp: "反対（はんたい）", vn: "phản đối" },
    { jp: "男性（だんせい）", vn: "nam giới" },
    { jp: "女性（じょせい）", vn: "nữ giới" },
    { jp: "〜によると", vn: "theo ~ (nguồn tin)" },
    { jp: "婚約します（こんやくします）", vn: "đính hôn" },
    { jp: "どうも", vn: "hình như, có vẻ (khi không chắc chắn)" }
  ],
};


