const vocabList_first = {
  vocabList_u_26: [
    { jp: "見る（みます）", vn: "xem, nhìn" },
    { jp: "診る（みます）", vn: "chẩn đoán, khám bệnh" },
    { jp: "捜す（さがします）", vn: "tìm đồ vật bị mất" },
    { jp: "探す（さがします）", vn: "tìm, tìm kiếm (cv, người…)" },
    { jp: "遅れる（おくれます）", vn: "trễ giờ" },
    { jp: "間に合います（まにあいます）", vn: "kịp giờ" },
    { jp: "宿題をやります（やります）", vn: "làm bài tập" },
    { jp: "拾います（ひろいます）", vn: "nhặt rác" },
    { jp: "連絡します（れんらくします）", vn: "liên lạc với trường học" },
    { jp: "気分がいい（きぶんがいい）", vn: "tâm trạng, thể trạng tốt" },
    { jp: "気分が悪い（きぶんがわるい）", vn: "tâm trạng, thể trạng xấu" },
    { jp: "運動会（うんどうかい）", vn: "hội thi thể thao" },
    { jp: "盆踊り（ぼんおどり）", vn: "lễ hội múa obon" },
    { jp: "フリーマーケット", vn: "chợ đồ cũ, chợ trời" },
    { jp: "場所（ばしょ）", vn: "nơi chốn, địa điểm" },
    { jp: "ボランティア", vn: "việc từ thiện, tình nguyện viên" },
    { jp: "財布（さいふ）", vn: "ví" },
    { jp: "ごみ", vn: "rác" },
    { jp: "国会議事堂（こっかいぎじどう）", vn: "tòa nhà quốc hội" },
    { jp: "平日（へいじつ）", vn: "ngày thường" },
    { jp: "大阪弁（おおさかべん）", vn: "tiếng Osaka, tiếng địa phương" },
    { jp: "今度（こんど）", vn: "lần tới" },
    { jp: "ずいぶん", vn: "khá, tương đối" },
    { jp: "直接（ちょくせつ）", vn: "trực tiếp" },
    { jp: "いつでも", vn: "lúc nào cũng" },
    { jp: "どこでも", vn: "ở đâu cũng" },
    { jp: "だれでも", vn: "ai cũng" },
    { jp: "なんでも", vn: "cái gì cũng" },
    { jp: "こんな…", vn: "...như thế này" },
    { jp: "そんな…", vn: "...như thế đó" },
    { jp: "あんな…", vn: "...như thế kia" },
    { jp: "片付く（かたづきます）", vn: "sắp xếp, dọn dẹp" },
    { jp: "出す（だします）", vn: "đổ, để (rác)" },
    { jp: "燃えるごみ（もえるごみ）", vn: "rác cháy được" },
    { jp: "置き場（おきば）", vn: "chỗ để, chỗ đặt" },
    { jp: "横（よこ）", vn: "bên cạnh" },
    { jp: "瓶（びん）", vn: "cái chai" },
    { jp: "缶（かん）", vn: "cái lon, hộp kim loại" },
    { jp: "ガス", vn: "ga" },
    { jp: "ガス会社（ガスがいしゃ）", vn: "công ty ga" },
    { jp: "宇宙（うちゅう）", vn: "vũ trụ" },
    { jp: "様（さま）", vn: "ngài, vị" },
    { jp: "宇宙船（うちゅうせん）", vn: "tàu vũ trụ" },
    { jp: "怖い（こわい）", vn: "sợ, đáng sợ" },
    { jp: "違います（ちがいます）", vn: "khác, không phải" },
    { jp: "宇宙飛行士（うちゅうひこうし）", vn: "nhà du hành vũ trụ" }
  ],
  vocabList_u_27: [
    { jp: "飼います（かいます）", vn: "nuôi, chăn nuôi" },
    { jp: "建てます（たてます）", vn: "xây dựng" },
    { jp: "走ります（はしります）", vn: "chạy" },
    { jp: "取ります（とります）", vn: "xin (nghỉ)" },
    { jp: "見えます（みえます）", vn: "có thể nhìn thấy" },
    { jp: "聞こえます（きこえます）", vn: "có thể nghe thấy" },
    { jp: "できます", vn: "được hoàn thành, được làm" },
    { jp: "開きます（ひらきます）", vn: "mở, tổ chức (lớp)" },
    { jp: "ペット", vn: "thú cưng, động vật nuôi" },
    { jp: "鳥（とり）", vn: "chim" },
    { jp: "こえ", vn: "tiếng, giọng nói" },
    { jp: "波（なみ）", vn: "sóng" },
    { jp: "花火（はなび）", vn: "pháo hoa" },
    { jp: "景色（けしき）", vn: "phong cảnh" },
    { jp: "昼間（ひるま）", vn: "ban ngày" },
    { jp: "昔（むかし）", vn: "ngày xưa" },
    { jp: "道具（どうぐ）", vn: "dụng cụ" },
    { jp: "自動販売機（じどうはんばいき）", vn: "máy bán hàng tự động" },
    { jp: "通信販売（つうしんはんばい）", vn: "thương mại viễn thông" },
    { jp: "クリーニング", vn: "giặt ủi" },
    { jp: "マンション", vn: "chung cư" },
    { jp: "台所（だいどころ）", vn: "nhà bếp" },
    { jp: "～後（～ご）", vn: "sau…" },
    { jp: "～しか", vn: "chỉ" },
    { jp: "～教室（～きょうしつ）", vn: "lớp học" },
    { jp: "パーティールーム", vn: "phòng tiệc" },
    { jp: "関西空港（かんさいくうこう）", vn: "sân bay Kansai" },
    { jp: "秋葉原（あきはばら）", vn: "khu bán đồ điện tử nổi tiếng ở Tokyo" },
    { jp: "伊豆（いず）", vn: "một đảo thuộc tỉnh Shizuoka" },
    { jp: "日曜日大工（にちようびだいく）", vn: "thợ mộc chủ nhật" },
    { jp: "本棚（ほんだな）", vn: "kệ sách, giá sách" },
    { jp: "いつか", vn: "một ngày nào đó" },
    { jp: "夢（ゆめ）", vn: "mơ" },
    { jp: "家（いえ）", vn: "nhà" },
    { jp: "素晴らしい（すばらしい）", vn: "tuyệt vời" },
    { jp: "子どもたち（こどもたち）", vn: "bọn trẻ" },
    { jp: "大好き（だいすき）", vn: "rất thích" },
    { jp: "漫画（まんが）", vn: "truyện tranh" },
    { jp: "主人公（しゅじんこう）", vn: "nhân vật chính" },
    { jp: "形（かたち）", vn: "hình dạng" },
    { jp: "ロボット", vn: "người máy" },
    { jp: "不思議な（ふしぎな）", vn: "kì lạ, thần bí" },
    { jp: "ポケット", vn: "túi" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "付けます（つけます）", vn: "lắp ghép" },
    { jp: "自由に（じゆうに）", vn: "tự do" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "飛びます（とびます）", vn: "bay" },
    { jp: "自分（じぶん）", vn: "tự mình" },
    { jp: "将来（しょうらい）", vn: "tương lai" },
    { jp: "他の / 外の（ほかの）", vn: "...khác" },
    { jp: "はっきり ", vn: "rõ ràng" }
  ],
  vocabList_u_28: [
    { jp: "売れます（うれます）", vn: "bán" },
    { jp: "踊ります（おどります）", vn: "nhảy" },
    { jp: "噛みます（かみます）", vn: "nhai, cắn" },
    { jp: "選びます（えらびます）", vn: "lựa, lựa chọn" },
    { jp: "通います（かよいます）", vn: "đi học (đại học)" },
    { jp: "メモします", vn: "ghi chép lại, ghi lại" },
    { jp: "真面目（まじめ）", vn: "nghiêm túc, đàng hoàng" },
    { jp: "熱心（ねっしん）", vn: "nhiệt tình" },
    { jp: "偉い（えらい）", vn: "vĩ đại, kính trọng" },
    { jp: "丁度いい（ちょうどいい）", vn: "vừa đúng, vừa vặn" },
    { jp: "優しい（やさしい）", vn: "hiền lành" },
    { jp: "習慣（しゅうかん）", vn: "tập quán" },
    { jp: "経験（けいけん）", vn: "kinh nghiệm" },
    { jp: "力（ちから）", vn: "sức mạnh" },
    { jp: "人気（にんき）", vn: "hâm mộ" },
    { jp: "形（かたち）", vn: "hình dáng" },
    { jp: "色（いろ）", vn: "màu sắc" },
    { jp: "味（あじ）", vn: "vị" },
    { jp: "ガム", vn: "kẹo cao su" },
    { jp: "品物（しなもの）", vn: "hàng hóa" },
    { jp: "値段（ねだん）", vn: "giá cả" },
    { jp: "給料（きゅうりょう）", vn: "lương" },
    { jp: "ボーナス", vn: "thưởng" },
    { jp: "番組（ばんぐみ）", vn: "chương trình (TV, phát thanh...)" },
    { jp: "ドラマ", vn: "kịch, phim truyền hình" },
    { jp: "小説（しょうせつ）", vn: "tiểu thuyết" },
    { jp: "小説家（しょうせつか）", vn: "tiểu thuyết gia" },
    { jp: "歌手（かしゅ）", vn: "ca sĩ" },
    { jp: "管理人（かんりにん）", vn: "người quản lý" },
    { jp: "息子（むすこ）", vn: "con trai (mình)" },
    { jp: "息子さん（むすこさん）", vn: "con trai (người khác)" },
    { jp: "娘（むすめ）", vn: "con gái (mình)" },
    { jp: "娘さん（むすめさん）", vn: "con gái (người khác)" },
    { jp: "自分（じぶん）", vn: "bản thân" },
    { jp: "将来（しょうらい）", vn: "tương lai" },
    { jp: "しばらく", vn: "một lát, một chút" },
    { jp: "たいてい", vn: "thường, thông thường" },
    { jp: "それに", vn: "ngoài ra" },
    { jp: "それで", vn: "do đó" },
    { jp: "「ちょっと」お願いがあるんですが", vn: "tôi có chút việc muốn nhờ" },
    { jp: "ホームステイ", vn: "homestay" },
    { jp: "会話（かいわ）", vn: "hội thoại" },
    { jp: "おしゃべりします", vn: "trò chuyện" },
    { jp: "お知らせ（おしらせ）", vn: "thông báo" },
    { jp: "日にち（ひにち）", vn: "ngày" },
    { jp: "土（ど）", vn: "thứ bảy" },
    { jp: "体育館（たいいくかん）", vn: "phòng thể dục" },
    { jp: "無料（むりょう）", vn: "miễn phí" },
  ],
  vocabList_u_29: [
    { jp: "開きます（あきます）", vn: "mở (cửa)" },
    { jp: "閉まります（しまります）", vn: "đóng (cửa)" },
    { jp: "点きます（つきます）", vn: "bật, sáng (đèn)" },
    { jp: "消えます（きえます）", vn: "tắt (đèn)" },
    { jp: "込みます（こみます）", vn: "đông (đường)" },
    { jp: "空きます（すきます）", vn: "vắng (đường)" },
    { jp: "壊れます（こわれます）", vn: "hỏng (ghế)" },
    { jp: "割れます（われます）", vn: "vỡ (cốc)" },
    { jp: "折れます（おれます）", vn: "gãy (cây)" },
    { jp: "破れます（やぶれます）", vn: "rách (giấy)" },
    { jp: "汚れます（よごれます）", vn: "dơ, bẩn (tay)" },
    { jp: "付きます（つきます）", vn: "dính, đính (có túi)" },
    { jp: "外れます（はずれます）", vn: "tuột, rời ra (nút)" },
    { jp: "止まります（とまります）", vn: "dừng" },
    { jp: "間違えます（まちがえます）", vn: "nhầm lẫn, sai" },
    { jp: "落とします（おとします）", vn: "làm rơi, rớt" },
    { jp: "掛かります（かかります）", vn: "khóa (đang bị khóa)" },
    { jp: "拭きます（ふきます）", vn: "lau (cửa)" },
    { jp: "取り替えます（とりかえます）", vn: "thay (pin)" },
    { jp: "片付けます（かたづけます）", vn: "dọn dẹp" },
    { jp: "皿（さら）", vn: "đĩa" },
    { jp: "茶碗（ちゃわん）", vn: "bát, chén" },
    { jp: "コップ", vn: "cốc" },
    { jp: "ガラス", vn: "ly (thủy tinh)" },
    { jp: "袋（ふくろ）", vn: "túi" },
    { jp: "書類（しょるい）", vn: "giấy tờ" },
    { jp: "枝（えだ）", vn: "cành cây" },
    { jp: "駅員（えきいん）", vn: "nhân viên nhà ga" },
    { jp: "交番（こうばん）", vn: "đồn cảnh sát" },
    { jp: "スピーチ", vn: "bài diễn văn" },
    { jp: "返事（へんじ）", vn: "trả lời" },
    { jp: "お先にどうぞ（おさきにどうぞ）", vn: "mời anh/chị cứ về trước" },
    { jp: "源氏物語（げんじものがたり）", vn: "Truyện Genji" },
    { jp: "今の電車（いまのでんしゃ）", vn: "tàu điện vừa chạy" },
    { jp: "忘れ物（わすれもの）", vn: "đồ bỏ quên" },
    { jp: "このくらい", vn: "cỡ tầm này" },
    { jp: "側（がわ）", vn: "phía..." },
    { jp: "ポケット", vn: "túi (quần áo)" },
    { jp: "辺（へん）", vn: "chỗ, vùng" },
    { jp: "覚えていません（おぼえていません）", vn: "tôi không nhớ" },
    { jp: "網棚（あみだな）", vn: "giá để hành lý" },
    { jp: "確か（たしか）", vn: "chắc là" },
    { jp: "ああ、よかった", vn: "ôi, may quá" },
    { jp: "地震（じしん）", vn: "động đất" },
    { jp: "壁（かべ）", vn: "bức tường" },
    { jp: "針（はり）", vn: "kim đồng hồ" },
    { jp: "指します（さします）", vn: "chỉ" },
    { jp: "駅前（えきまえ）", vn: "trước ga" },
    { jp: "倒れます（たおれます）", vn: "đổ (ngã, sập...)" },
    { jp: "西の方（にしのほう）", vn: "phía tây" },
    { jp: "燃えます（もえます）", vn: "cháy" }
  ],
  vocabList_u_30: [
    { jp: "はります", vn: "dán" },
    { jp: "掛けます（かけます）", vn: "treo" },
    { jp: "飾ります（かざります）", vn: "trang trí" },
    { jp: "並べます（ならべます）", vn: "xếp thành hàng" },
    { jp: "植えます（うえます）", vn: "trồng (cây)" },
    { jp: "戻します（もどします）", vn: "đưa về, trả về" },
    { jp: "まとめます", vn: "nhóm lại, tóm tắt" },
    { jp: "方づけます（かたづけます）", vn: "dọn dẹp, sắp xếp" },
    { jp: "しまいます", vn: "cất vào, để vào" },
    { jp: "決めます（きめます）", vn: "quyết định" },
    { jp: "知らせます（しらせます）", vn: "thông báo" },
    { jp: "祖横断します（そうだんします）", vn: "thảo luận, trao đổi , bàn bạc" },
    { jp: "予習します（よしゅうします）", vn: "chuẩn bị bài mới" },
    { jp: "復習します（ふくしゅうします）", vn: "ôn bài cũ" },
    { jp: "そのままにします", vn: "để nguyên như thế" },
    { jp: "お子さん（おこさん）", vn: "con (dùng đối với người khác)" },
    { jp: "授業（じゅぎょう）", vn: "giờ học" },
    { jp: "講義（こうぎ）", vn: "bài giảng" },
    { jp: "ミーティング", vn: "cuộc họp" },
    { jp: "予定（よてい）", vn: "kế hoạch, dự định" },
    { jp: "お知らせ（おしらせ）", vn: "bản thông báo" },
    { jp: "案内書（あんないしょ）", vn: "tài liệu hướng dẫn" },
    { jp: "カレンダー", vn: "lịch , tờ lịch" },
    { jp: "ポスター", vn: "tờ quảng cáo, tờ áp phích" },
    { jp: "ごみ箱（ごみばこ）", vn: "thùng rác" },
    { jp: "人形（にんぎょう）", vn: "con búp bê, con rối" },
    { jp: "花瓶（かびん）", vn: "lọ hoa" },
    { jp: "鏡（かがみ）", vn: "cái gương" },
    { jp: "引き出し（ひきだし）", vn: "ngăn kéo" },
    { jp: "玄関（げんかん）", vn: "cửa vào" },
    { jp: "廊下（ろうか）", vn: "hành lang" },
    { jp: "壁（かべ）", vn: "bức tường" },
    { jp: "池（いけ）", vn: "cái ao" },
    { jp: "交番（こうばん）", vn: "trạm cảnh sát" },
    { jp: "元の所（もとのところ）", vn: "địa điểm ban đầu" },
    { jp: "周り（まわり）", vn: "xung quanh" },
    { jp: "真ん中（まんなか）", vn: "giữa, trung tâm" },
    { jp: "すみ", vn: "góc" },
    { jp: "まだ", vn: "chưa" },
    { jp: "―ほど", vn: "chừng—" },
    { jp: "予定表（よていひょう）", vn: "thời khóa biểu" },
    { jp: "ご苦労さま（ごくろうさま）", vn: "anh, chị đã làm việc vất vả/cảm ơn anh, chị" },
    { jp: "希望（きぼう）", vn: "hi vọng, nguyện vọng" },
    { jp: "何かご希望がありますか（なにかごきぼうがありますか）", vn: "anh/chị có nguyện vọng gì không?" },
    { jp: "ミュージカル", vn: "ca kịch" },
    { jp: "それはいいですな", vn: "Hay quá nhỉ" },
    { jp: "丸い（まるい）", vn: "tròn" },
    { jp: "月（つき）", vn: "mặt trăng" },
    { jp: "地球（ちきゅう）", vn: "trái đất" },
    { jp: "うれしい", vn: "vui" },
    { jp: "いや（な）", vn: "chán, ghét, không chấp nhận được" },
    { jp: "すると", vn: "sau đó, tiếp đó" },
    { jp: "目が覚めます（めがさめます）", vn: "tỉnh giấc, mở mắt" }
  ],
  vocabList_u_31: [
    { jp: "始まります（はじまります）", vn: "bắt đầu (buổi lễ ~)" },
    { jp: "続けます（つづけます）", vn: "tiếp tục" },
    { jp: "見つめます（みつけます）", vn: "tìm thấy" },
    { jp: "受けます（うけます）", vn: "thi (kì thi)" },
    { jp: "入学します（にゅうがくします）", vn: "nhập học" },
    { jp: "卒業します（そつぎょうします）", vn: "tốt nghiệp" },
    { jp: "休憩します（きゅうけいします）", vn: "giải lao" },
    { jp: "連休（れんきゅう）", vn: "ngày nghỉ liền nhau" },
    { jp: "作文（さくぶん）", vn: "bài văn" },
    { jp: "展覧会（てんらんかい）", vn: "triển lãm" },
    { jp: "結婚式（けっこんしき）", vn: "lễ cưới, đám cưới" },
    { jp: "葬式（そうしき）", vn: "lễ tang, đám tang" },
    { jp: "式（しき）", vn: "buổi lễ" },
    { jp: "本社（ほんしゃ）", vn: "trụ sở chính" },
    { jp: "支店（してん）", vn: "chi nhánh" },
    { jp: "教会（きょうかい）", vn: "nhà thờ" },
    { jp: "大学院（だいがくいん）", vn: "cao học, cơ sở giáo dục trên đại học" },
    { jp: "動物園（どうぶつえん）", vn: "sở thú" },
    { jp: "温泉（おんせん）", vn: "suối nước nóng" },
    { jp: "お客さん（おきゃくさん）", vn: "khách hàng" },
    { jp: "だれか", vn: "ai đó" },
    { jp: "～の方（～のほう）", vn: "hướng~" },
    { jp: "ずっと", vn: "suốt, liền" },
    { jp: "残ります（のこります）", vn: "ở lại, còn" },
    { jp: "月に（つきに）", vn: "(trong) một tháng" },
    { jp: "普通の（ふつうの）", vn: "thường" },
    { jp: "インターネット", vn: "internet" },
    { jp: "村（むら）", vn: "làng" },
    { jp: "映画館（えいがかん）", vn: "rạp chiếu phim" },
    { jp: "いや（な）", vn: "chán ghét, không chấp nhận được" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "閉じます（とじます）", vn: "nhắm" },
    { jp: "都会（とかい）", vn: "thành phố" },
    { jp: "子供たち（こどもたち）", vn: "bọn trẻ" },
    { jp: "自由に（じゆうに）", vn: "tự do" },
    { jp: "世界中（せかいじゅう）", vn: "khắp thế giới" },
    { jp: "集まります（あつまります）", vn: "tập hợp" },
    { jp: "美しい（うつくしい）", vn: "đẹp" },
    { jp: "自然（しぜん）", vn: "thiên nhiên, tự nhiên" },
    { jp: "すばらしさ", vn: "tuyệt vời" },
    { jp: "気が付きます（きがつきます）", vn: "để ý, nhận ra" }
  ],
  vocabList_u_32: [
    { jp: "運動します（うんどうします）", vn: "vận động, tập thể thao" },
    { jp: "成功します（せいこうします）", vn: "thành công" },
    { jp: "失敗します（しっぱいします）", vn: "thất bại, trượt" },
    { jp: "合格します（ごうかくします）", vn: "đỗ" },
    { jp: "戻ります（もどります）", vn: "quay lại, trở lại" },
    { jp: "やみます（雨が～）", vn: "tạnh, ngừng" },
    { jp: "晴れます（はれます）", vn: "nắng, quang đãng" },
    { jp: "曇ります（くもります）", vn: "có mây, mây mù" },
    { jp: "吹きます（ふきます）", vn: "thổi" },
    { jp: "治ります・直ります（なおります）", vn: "khỏi" },
    { jp: "続きます（つづきます）", vn: "tiếp tục, tiếp diễn" },
    { jp: "冷やします（ひやします）", vn: "làm lạnh" },
    { jp: "心配（しんぱい）", vn: "lo lắng" },
    { jp: "十分（じゅうぶん）", vn: "đủ" },
    { jp: "おかしい", vn: "có vấn đề, không bình thường" },
    { jp: "うるさい", vn: "ồn ào" },
    { jp: "やけど", vn: "bỏng" },
    { jp: "けが", vn: "bị thương" },
    { jp: "せき", vn: "ho" },
    { jp: "インフルエンザ", vn: "cúm dịch" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "太陽（たいよう）", vn: "mặt trời" },
    { jp: "星（ほし）", vn: "ngôi sao" },
    { jp: "月（つき）", vn: "mặt trăng" },
    { jp: "風（かぜ）", vn: "gió" },
    { jp: "北（きた）", vn: "phía bắc" },
    { jp: "南（みなみ）", vn: "phía nam" },
    { jp: "西（にし）", vn: "phía tây" },
    { jp: "東（ひがし）", vn: "phía đông" },
    { jp: "隧道（すいどう）", vn: "nước máy" },
    { jp: "エンジン", vn: "động cơ" },
    { jp: "チーム", vn: "đội" },
    { jp: "今夜（こんや）", vn: "tối nay, đêm nay" },
    { jp: "夕方（ゆうがた）", vn: "chiều tối" },
    { jp: "前（まえ）", vn: "trước" },
    { jp: "遅く（おそく）", vn: "muộn, khuya" },
    { jp: "こんなに", vn: "như thế này" },
    { jp: "そんなに", vn: "như thế đó" },
    { jp: "あんなに", vn: "như thế kia" },
    { jp: "もしかしたら", vn: "có thể, biết đâu là, có khả năng" },
    { jp: "それはいけませんね", vn: "thế thì thật không tốt" },
    { jp: "オリンピック", vn: "Olympic" },
    { jp: "元気（げんき）", vn: "khỏe mạnh" },
    { jp: "胃（い）", vn: "dạ dày" },
    { jp: "働きすぎ（はたらきすぎ）", vn: "làm việc quá sức" },
    { jp: "ストレス", vn: "căng thẳng tâm lý" },
    { jp: "無理をします（むりをします）", vn: "làm quá sức" },
    { jp: "ゆっくりします", vn: "nghỉ ngơi, thư thái, dưỡng sức" },
    { jp: "星占い（ほしうらない）", vn: "bói sao" },
    { jp: "牡牛座（おうしざ）", vn: "chòm sao Kim Ngưu" },
    { jp: "困ります（こまります）", vn: "rắc rối, khó xử, có vấn đề" },
    { jp: "宝くじ（たからくじ）", vn: "xổ số" },
    { jp: "当たります（あたります）", vn: "trúng (số)" },
    { jp: "健康（けんこう）", vn: "sức khỏe" },
    { jp: "恋愛（れんあい）", vn: "tình yêu" },
    { jp: "恋人（こいびと）", vn: "người yêu" },
    { jp: "金持ち（かねもち）", vn: "người giàu có" }
  ],
  vocabList_u_33: [
    { jp: "逃げます（にげます）", vn: "chạy trốn, bỏ chạy" },
    { jp: "騒ぎます（さわぎます）", vn: "làm ồn, làm rùm beng" },
    { jp: "あきらめます", vn: "từ bỏ, đầu hàng" },
    { jp: "投げます（なげます）", vn: "ném" },
    { jp: "守ります（まもります）", vn: "bảo vệ, tuân thủ" },
    { jp: "上げます（あげます）", vn: "nâng lên, tăng lên" },
    { jp: "下げます（さげます）", vn: "hạ xuống, giảm xuống" },
    { jp: "伝えます（つたえます）", vn: "truyền đạt" },
    { jp: "注意します（ちゅういします）", vn: "chú ý" },
    { jp: "外します（はずします）", vn: "rời, không có ở (chỗ ngồi)" },
    { jp: "だめ", vn: "không được, không thể" },
    { jp: "席（せき）", vn: "chỗ ngồi, ghế" },
    { jp: "ファイト", vn: "‘quyết chiến’, ‘cố lên’" },
    { jp: "マーク", vn: "kí hiệu" },
    { jp: "ボール", vn: "quả bóng" },
    { jp: "洗濯機（せんたくき）", vn: "máy giặt" },
    { jp: "ー機（ーき）", vn: "máy–" },
    { jp: "規則（きそく）", vn: "quy tắc, kỷ luật" },
    { jp: "使用禁止（しようきんし）", vn: "cấm sử dụng" },
    { jp: "立ち入り禁止（たちいりきんし）", vn: "cấm vào" },
    { jp: "入口（いりぐち）", vn: "cửa vào" },
    { jp: "出口（でぐち）", vn: "cửa ra" },
    { jp: "非常口（ひじょうぐち）", vn: "cửa thoát hiểm" },
    { jp: "無料（むりょう）", vn: "miễn phí" },
    { jp: "本日休業（ほんじつきゅうぎょう）", vn: "hôm nay đóng cửa, hôm nay nghỉ" },
    { jp: "営業中（えいぎょうちゅう）", vn: "đang mở cửa" },
    { jp: "使用中（しようちゅう）", vn: "đang sử dụng" },
    { jp: "ー中（ーちゅう）", vn: "đang–" },
    { jp: "どういうー", vn: "–gì, –thế nào" },
    { jp: "もう", vn: "không—nữa" },
    { jp: "あと", vn: "còn~" },
    { jp: "駐車違反（ちゅうしゃいはん）", vn: "đỗ xe trái phép" },
    { jp: "そりゃあ", vn: "thế thì, ồ" },
    { jp: "～以内（～いない）", vn: "~trong khoảng, ~trong vòng" },
    { jp: "警察（けいさつ）", vn: "cảnh sát" },
    { jp: "罰金（ばっきん）", vn: "tiền phạt" },
    { jp: "電報（でんぽう）", vn: "điện báo" },
    { jp: "人々（ひとびと）", vn: "nhiều người" },
    { jp: "急用（きゅうよう）", vn: "việc gấp" },
    { jp: "打ちます（うちます）（電報を）", vn: "gửi (điện báo)" },
    { jp: "電報代（でんぽうだい）", vn: "phí điện báo" },
    { jp: "できるだけ", vn: "cố gắng, trong khả năng có thể" },
    { jp: "短く（みじかく）", vn: "ngắn gọn" },
    { jp: "また", vn: "thêm nữa" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "危篤（キトク）", vn: "tình trạng hiểm nghèo" },
    { jp: "重い病気（おもいびょうき）", vn: "bệnh nặng" },
    { jp: "明日（あす）", vn: "ngày mai" },
    { jp: "留守（るす）", vn: "vắng nhà" },
    { jp: "留守番（るすばん）", vn: "trông nhà, giữ nhà" },
    { jp: "（お）祝い（おいわい）", vn: "việc mừng" },
    { jp: "なくなります", vn: "mất, chết" },
    { jp: "悲しい（かなしい）", vn: "buồn" },
    { jp: "利用します（りようします）", vn: "sử dụng, lợi dụng, tận dụng" }
  ],
  vocabList_u_34: [
    { jp: "みがきます（磨きます）", vn: "mài, đánh (răng)" },
    { jp: "くみたてます（組み立てます）", vn: "lắp ráp, lắp đặt" },
    { jp: "おります（折ります）", vn: "gấp, gập, bẻ gãy" },
    { jp: "きがつきます（気が付きます）", vn: "nhận thấy, phát hiện" },
    { jp: "つけます（付けます）", vn: "chấm" },
    { jp: "みつかります（見つかります）", vn: "được tìm thấy" },
    { jp: "します（ネクタイを）", vn: "đeo , thắt" },
    { jp: "しつもんします（質問します）", vn: "hỏi" },
    { jp: "ほそい（細い）", vn: "gầy, hẹp, thon" },
    { jp: "ふとい（太い）", vn: "béo, to" },
    { jp: "ぼんおどり（盆踊り）", vn: "múa trong hội bon" },
    { jp: "スポーツクラブ", vn: "câu lạc bộ thể thao" },
    { jp: "かぐ（家具）", vn: "gia cụ , đồ dùng nội thất" },
    { jp: "キー", vn: "chìa khóa" },
    { jp: "シートべルト", vn: "dây an toàn" },
    { jp: "せつめいしょ（説明書）", vn: "quyển hướng dẫn" },
    { jp: "ず（図）", vn: "sơ đồ, hình vẽ" },
    { jp: "せん（線）", vn: "đường" },
    { jp: "やじるし（矢印）", vn: "dấu mũi tên" },
    { jp: "くろ（黒）", vn: "màu đen" },
    { jp: "しろ（白）", vn: "màu trắng" },
    { jp: "あか（赤）", vn: "màu đỏ" },
    { jp: "あお（青）", vn: "màu xanh da trời" },
    { jp: "こん（紺）", vn: "màu xanh lam" },
    { jp: "きいろ（黄色）", vn: "màu vàng" },
    { jp: "ちゃいろ（茶色）", vn: "màu nâu" },
    { jp: "しょうゆ", vn: "xì dầu" },
    { jp: "ソース", vn: "nước chấm, nước xốt" },
    { jp: "ゆうべ", vn: "tối qua, đêm qua" },
    { jp: "さっき", vn: "vừa rồi, vừa lúc nãy" },
    { jp: "さどう（茶道）", vn: "trà đạo" },
    { jp: "おちゃをたてます（お茶をたてます）", vn: "pha trà" },
    { jp: "さきに（先に）", vn: "trước" },
    { jp: "のせます（載せます）", vn: "đặt lên" },
    { jp: "これでいいですか", vn: "Thế này được không/đã được chưa" },
    { jp: "にがい（苦い）", vn: "đắng" },
    { jp: "おやこどんぶり（親子どんぶり）", vn: "món oyako-don" },
    { jp: "ざいりょう（材料）", vn: "nguyên liệu" },
    { jp: "ーぶん（－分）", vn: "ーphần (biểu thị lượng)" },
    { jp: "とりにく（鶏肉）", vn: "thịt gà" },
    { jp: "ーグラム", vn: "gam" },
    { jp: "たまねぎ", vn: "hành củ" },
    { jp: "４ぶんの１（４分の１）", vn: "1/4 (một phần tư)" },
    { jp: "ちょうみりょう（調味料）", vn: "gia vị" },
    { jp: "なべ", vn: "nồi" },
    { jp: "ひ（火）", vn: "lửa" },
    { jp: "ひにかけます（火にかけます）", vn: "đun" },
    { jp: "にます（煮ます）", vn: "nấu" },
    { jp: "にえます（煮えます）", vn: "chín, được nấu" },
    { jp: "どんぶり", vn: "bát ô tô lớn" }
  ],
};


