const vocabList_first = {
  vocabList_u_26: [
    { jp: "見る（みます）", vn: "xem, nhìn" },
    { jp: "診る（みます）", vn: "chẩn đoán, khám bệnh" },
    { jp: "捜す（さがします）", vn: "tìm đồ vật bị mất" },
    { jp: "探す（さがします）", vn: "tìm, tìm kiếm (cv, người…)" },
    { jp: "遅れる（おくれます）", vn: "trễ giờ" },
    { jp: "間に合います（まにあいます）", vn: "kịp giờ" },
    { jp: "宿題をやります（やります）", vn: "làm bài tập" },
    { jp: "拾います（ひろいます）", vn: "nhặt rác" },
    { jp: "連絡します（れんらくします）", vn: "liên lạc với trường học" },
    { jp: "気分がいい（きぶんがいい）", vn: "tâm trạng, thể trạng tốt" },
    { jp: "気分が悪い（きぶんがわるい）", vn: "tâm trạng, thể trạng xấu" },
    { jp: "運動会（うんどうかい）", vn: "hội thi thể thao" },
    { jp: "盆踊り（ぼんおどり）", vn: "lễ hội múa obon" },
    { jp: "フリーマーケット", vn: "chợ đồ cũ, chợ trời" },
    { jp: "場所（ばしょ）", vn: "nơi chốn, địa điểm" },
    { jp: "ボランティア", vn: "việc từ thiện, tình nguyện viên" },
    { jp: "財布（さいふ）", vn: "ví" },
    { jp: "ごみ", vn: "rác" },
    { jp: "国会議事堂（こっかいぎじどう）", vn: "tòa nhà quốc hội" },
    { jp: "平日（へいじつ）", vn: "ngày thường" },
    { jp: "大阪弁（おおさかべん）", vn: "tiếng Osaka, tiếng địa phương" },
    { jp: "今度（こんど）", vn: "lần tới" },
    { jp: "ずいぶん", vn: "khá, tương đối" },
    { jp: "直接（ちょくせつ）", vn: "trực tiếp" },
    { jp: "いつでも", vn: "lúc nào cũng" },
    { jp: "どこでも", vn: "ở đâu cũng" },
    { jp: "だれでも", vn: "ai cũng" },
    { jp: "なんでも", vn: "cái gì cũng" },
    { jp: "こんな…", vn: "...như thế này" },
    { jp: "そんな…", vn: "...như thế đó" },
    { jp: "あんな…", vn: "...như thế kia" },
    { jp: "片付く（かたづきます）", vn: "sắp xếp, dọn dẹp" },
    { jp: "出す（だします）", vn: "đổ, để (rác)" },
    { jp: "燃えるごみ（もえるごみ）", vn: "rác cháy được" },
    { jp: "置き場（おきば）", vn: "chỗ để, chỗ đặt" },
    { jp: "横（よこ）", vn: "bên cạnh" },
    { jp: "瓶（びん）", vn: "cái chai" },
    { jp: "缶（かん）", vn: "cái lon, hộp kim loại" },
    { jp: "ガス", vn: "ga" },
    { jp: "ガス会社（ガスがいしゃ）", vn: "công ty ga" },
    { jp: "宇宙（うちゅう）", vn: "vũ trụ" },
    { jp: "様（さま）", vn: "ngài, vị" },
    { jp: "宇宙船（うちゅうせん）", vn: "tàu vũ trụ" },
    { jp: "怖い（こわい）", vn: "sợ, đáng sợ" },
    { jp: "違います（ちがいます）", vn: "khác, không phải" },
    { jp: "宇宙飛行士（うちゅうひこうし）", vn: "nhà du hành vũ trụ" }
  ],
  vocabList_u_27: [
    { jp: "飼います（かいます）", vn: "nuôi, chăn nuôi" },
    { jp: "建てます（たてます）", vn: "xây dựng" },
    { jp: "走ります（はしります）", vn: "chạy" },
    { jp: "取ります（とります）", vn: "xin (nghỉ)" },
    { jp: "見えます（みえます）", vn: "có thể nhìn thấy" },
    { jp: "聞こえます（きこえます）", vn: "có thể nghe thấy" },
    { jp: "できます", vn: "được hoàn thành, được làm" },
    { jp: "開きます（ひらきます）", vn: "mở, tổ chức (lớp)" },
    { jp: "ペット", vn: "thú cưng, động vật nuôi" },
    { jp: "鳥（とり）", vn: "chim" },
    { jp: "こえ", vn: "tiếng, giọng nói" },
    { jp: "波（なみ）", vn: "sóng" },
    { jp: "花火（はなび）", vn: "pháo hoa" },
    { jp: "景色（けしき）", vn: "phong cảnh" },
    { jp: "昼間（ひるま）", vn: "ban ngày" },
    { jp: "昔（むかし）", vn: "ngày xưa" },
    { jp: "道具（どうぐ）", vn: "dụng cụ" },
    { jp: "自動販売機（じどうはんばいき）", vn: "máy bán hàng tự động" },
    { jp: "通信販売（つうしんはんばい）", vn: "thương mại viễn thông" },
    { jp: "クリーニング", vn: "giặt ủi" },
    { jp: "マンション", vn: "chung cư" },
    { jp: "台所（だいどころ）", vn: "nhà bếp" },
    { jp: "～後（～ご）", vn: "sau…" },
    { jp: "～しか", vn: "chỉ" },
    { jp: "～教室（～きょうしつ）", vn: "lớp học" },
    { jp: "パーティールーム", vn: "phòng tiệc" },
    { jp: "関西空港（かんさいくうこう）", vn: "sân bay Kansai" },
    { jp: "秋葉原（あきはばら）", vn: "khu bán đồ điện tử nổi tiếng ở Tokyo" },
    { jp: "伊豆（いず）", vn: "một đảo thuộc tỉnh Shizuoka" },
    { jp: "日曜日大工（にちようびだいく）", vn: "thợ mộc chủ nhật" },
    { jp: "本棚（ほんだな）", vn: "kệ sách, giá sách" },
    { jp: "いつか", vn: "một ngày nào đó" },
    { jp: "夢（ゆめ）", vn: "mơ" },
    { jp: "家（いえ）", vn: "nhà" },
    { jp: "素晴らしい（すばらしい）", vn: "tuyệt vời" },
    { jp: "子どもたち（こどもたち）", vn: "bọn trẻ" },
    { jp: "大好き（だいすき）", vn: "rất thích" },
    { jp: "漫画（まんが）", vn: "truyện tranh" },
    { jp: "主人公（しゅじんこう）", vn: "nhân vật chính" },
    { jp: "形（かたち）", vn: "hình dạng" },
    { jp: "ロボット", vn: "người máy" },
    { jp: "不思議な（ふしぎな）", vn: "kì lạ, thần bí" },
    { jp: "ポケット", vn: "túi" },
    { jp: "例えば（たとえば）", vn: "ví dụ" },
    { jp: "付けます（つけます）", vn: "lắp ghép" },
    { jp: "自由に（じゆうに）", vn: "tự do" },
    { jp: "空（そら）", vn: "bầu trời" },
    { jp: "飛びます（とびます）", vn: "bay" },
    { jp: "自分（じぶん）", vn: "tự mình" },
    { jp: "将来（しょうらい）", vn: "tương lai" },
    { jp: "ほかの（他の / 外の）", vn: "...khác" },
    { jp: "はっきり ", vn: "rõ ràng" }
  ],
  vocabList_u_28: [
    { jp: "うれます", kanji: "売れます", vn: "bán" },
    { jp: "おどります", kanji: "踊ります", vn: "nhảy" },
    { jp: "かみます", kanji: "", vn: "nhai, cắn" },
    { jp: "えらびます", kanji: "選びます", vn: "lựa, lựa chọn" },
    { jp: "かよいます", kanji: "通います", vn: "đi học (đại học)" },
    { jp: "メモします", kanji: "メモします", vn: "ghi chép lại, ghi lại" },
    { jp: "まじめ", kanji: "真面目", vn: "nghiêm túc, đàng hoàng" },
    { jp: "ねっしん", kanji: "熱心", vn: "nhiệt tình" },
    { jp: "えらい", kanji: "偉い", vn: "vĩ đại, kính trọng" },
    { jp: "ちょうどいい", kanji: "丁度いい", vn: "vừa đúng, vừa vặn" },
    { jp: "やさしい", kanji: "優しい", vn: "hiền lành" },
    { jp: "しゅうかん", kanji: "習慣", vn: "tập quán" },
    { jp: "けいけん", kanji: "経験", vn: "kinh nghiệm" },
    { jp: "ちから", kanji: "力", vn: "sức mạnh" },
    { jp: "にんき", kanji: "人気", vn: "hâm mộ" },
    { jp: "かたち", kanji: "形", vn: "hình dáng" },
    { jp: "いろ", kanji: "色", vn: "màu sắc" },
    { jp: "あじ", kanji: "味", vn: "vị" },
    { jp: "ガム", kanji: "", vn: "kẹo cao su" },
    { jp: "しなもの", kanji: "品物", vn: "hàng hóa" },
    { jp: "ねだん", kanji: "値段", vn: "giá cả" },
    { jp: "きゅうりょう", kanji: "給料", vn: "lương" },
    { jp: "ボーナス", kanji: "", vn: "thưởng" },
    { jp: "ばんぐみ", kanji: "番組", vn: "chương trình (TV, phát thanh...)" },
    { jp: "ドラマ", kanji: "", vn: "kịch, phim truyền hình" },
    { jp: "しょうせつ", kanji: "小説", vn: "tiểu thuyết" },
    { jp: "しょうせつか", kanji: "小説家", vn: "tiểu thuyết gia" },
    { jp: "かしゅ", kanji: "歌手", vn: "ca sĩ" },
    { jp: "かんりにん", kanji: "管理人", vn: "người quản lý" },
    { jp: "むすこ", kanji: "息子", vn: "con trai (mình)" },
    { jp: "むすこさん", kanji: "息子さん", vn: "con trai (người khác)" },
    { jp: "むすめ", kanji: "娘", vn: "con gái (mình)" },
    { jp: "むすめさん", kanji: "娘さん", vn: "con gái (người khác)" },
    { jp: "じぶん", kanji: "自分", vn: "bản thân" },
    { jp: "しょうらい", kanji: "将来", vn: "tương lai" },
    { jp: "しばらく", kanji: "", vn: "một lát, một chút" },
    { jp: "たいてい", kanji: "", vn: "thường, thông thường" },
    { jp: "それに", kanji: "", vn: "ngoài ra" },
    { jp: "それで", kanji: "", vn: "do đó" },
    { jp: "「ちょっと」お願いがあるんですが", kanji: "", vn: "tôi có chút việc muốn nhờ" },
    { jp: "ホームステイ", kanji: "", vn: "homestay" },
    { jp: "かいわ", kanji: "会話", vn: "hội thoại" },
    { jp: "おしゃべりします", kanji: "", vn: "trò chuyện" },
    { jp: "おしらせ", kanji: "お知らせ", vn: "thông báo" },
    { jp: "ひにち", kanji: "日にち", vn: "ngày" },
    { jp: "ど", kanji: "土", vn: "thứ bảy" },
    { jp: "たいいくかん", kanji: "体育館", vn: "phòng thể dục" },
    { jp: "むりょう", kanji: "無料", vn: "miễn phí" }
  ]
};


