const vocabList_n3 = [
   //1-50
   { jp: "男性（だんせい）", vn: "Nam giới" },
   { jp: "女性（じょせい）", vn: "Nữ giới" },
   { jp: "高齢（こうれい）", vn: "Tuổi cao" },
   { jp: "年上（としうえ）", vn: "Người lớn tuổi hơn" },
   { jp: "目上（めうえ）", vn: "Cấp trên" },
   { jp: "先輩（せんぱい）", vn: "Tiền bối, đàn anh" },
   { jp: "後輩（こうはい）", vn: "Hậu bối, đàn em" },
   { jp: "上司（じょうし）", vn: "Cấp trên" },
   { jp: "相手（あいて）", vn: "Đối phương, đối thủ" },
   { jp: "知り合い（しりあい）", vn: "Người quen" },
   { jp: "友人（ゆうじん）", vn: "Bạn bè" },
   { jp: "仲（なか）", vn: "Quan hệ" },
   { jp: "生年月日（せいねんがっぴ）", vn: "Ngày tháng năm sinh" },
   { jp: "誕生（たんじょう）", vn: "Sự ra đời" },
   { jp: "年（とし）", vn: "Năm, tuổi" },
   { jp: "出身（しゅっしん）", vn: "Xuất thân, quê quán" },
   { jp: "故郷（こきょう）", vn: "Quê hương, quê nhà" },
   { jp: "成長（せいちょう）", vn: "Tăng trưởng, trưởng thành" },
   { jp: "成人（せいじん）", vn: "Người trưởng thành" },
   { jp: "合格（ごうかく）", vn: "Đỗ (đại học, kỳ thi, kiểm tra)" },
   { jp: "進学（しんがく）", vn: "Học lên cao hơn, học lên đại học" },
   { jp: "退学（たいがく）", vn: "Bỏ học, thôi học" },
   { jp: "就職（しゅうしょく）", vn: "Tìm việc, xin việc" },
   { jp: "退職（たいしょく）", vn: "Nghỉ việc" },
   { jp: "失業（しつぎょう）", vn: "Thất nghiệp" },
   { jp: "残業（ざんぎょう）", vn: "Làm thêm giờ, làm việc ngoài giờ" },
   { jp: "生活（せいかつ）", vn: "Sinh sống, sinh hoạt" },
   { jp: "通勤（つうきん）", vn: "Sự đi làm" },
   { jp: "学歴（がくれき）", vn: "Quá trình học hành, bằng cấp" },
   { jp: "給料（きゅうりょう）", vn: "Tiền lương" },
   { jp: "面接（めんせつ）", vn: "Phỏng vấn" },
   { jp: "休憩（きゅうけい）", vn: "Nghỉ giải lao" },
   { jp: "観光（かんこう）", vn: "Du lịch, thăm quan" },
   { jp: "帰国（きこく）", vn: "Về nước" },
   { jp: "帰省（きせい）", vn: "Về quê" },
   { jp: "帰宅（きたく）", vn: "Về nhà" },
   { jp: "参加（さんか）", vn: "Tham gia" },
   { jp: "出席（しゅっせき）", vn: "Có mặt, tham dự" },
   { jp: "欠席（けっせき）", vn: "Vắng mặt" },
   { jp: "遅刻（ちこく）", vn: "Muộn, đến muộn" },
   { jp: "化粧（けしょう）", vn: "Trang điểm" },
   { jp: "計算（けいさん）", vn: "Tính toán" },
   { jp: "計画（けいかく）", vn: "Kế hoạch" },
   { jp: "成功（せいこう）", vn: "Thành công" },
   { jp: "失敗（しっぱい）", vn: "Thất bại" },
   { jp: "準備（じゅんび）", vn: "Chuẩn bị" },
   { jp: "整理（せいり）", vn: "Thu xếp, chỉnh sửa, cắt giảm" },
   { jp: "注文（ちゅうもん）", vn: "Đặt hàng, gọi món" },
   { jp: "貯金（ちょきん）", vn: "Tiền tiết kiệm" },
   { jp: "徹夜（てつや）", vn: "Thức trắng cả đêm, thức đêm" },
   //51-100
   { jp: "引っ越し（ひっこし）", vn: "Chuyển nhà" },
   { jp: "身長（しんちょう）", vn: "Chiều cao" },
   { jp: "体重（たいじゅう）", vn: "Cân nặng" },
   { jp: "けが（けが）", vn: "Vết thương" },
   { jp: "会（かい）", vn: "Tiệc, liên hoan" },
   { jp: "趣味（しゅみ）", vn: "Sở thích" },
   { jp: "興味（きょうみ）", vn: "Hứng thú" },
   { jp: "思い出（おもいで）", vn: "Kỷ niệm, hồi ức" },
   { jp: "冗談（じょうだん）", vn: "Đùa, nói đùa" },
   { jp: "目的（もくてき）", vn: "Mục đích" },
   { jp: "約束（やくそく）", vn: "Lời hứa, cuộc hẹn" },
   { jp: "お喋り（おしゃべり）", vn: "Nói chuyện, lắm lời" },
   { jp: "遠慮（えんりょ）", vn: "Ngại, khách khí, kiềm chế" },
   { jp: "我慢（がまん）", vn: "Nhẫn nhịn, chịu đựng" },
   { jp: "迷惑（めいわく）", vn: "Làm phiền, quấy rầy" },
   { jp: "希望（きぼう）", vn: "Hy vọng, ý muốn" },
   { jp: "夢（ゆめ）", vn: "Giấc mơ, ước mơ" },
   { jp: "賛成（さんせい）", vn: "Tán thành, ủng hộ" },
   { jp: "反対（はんたい）", vn: "Phản đối" },
   { jp: "想像（そうぞう）", vn: "Tưởng tượng" },
   { jp: "努力（どりょく）", vn: "Cố gắng, nỗ lực" },
   { jp: "太陽（たいよう）", vn: "Mặt trời" },
   { jp: "地球（ちきゅう）", vn: "Trái đất" },
   { jp: "温度（おんど）", vn: "Nhiệt độ" },
   { jp: "湿度（しつど）", vn: "Độ ẩm" },
   { jp: "湿気（しっけ）", vn: "Hơi ẩm" },
   { jp: "梅雨（つゆ）", vn: "Mùa mưa" },
   { jp: "かび（かび）", vn: "Mốc" },
   { jp: "暖房（だんぼう）", vn: "Máy sưởi" },
   { jp: "皮（かわ）", vn: "Da, vỏ" },
   { jp: "缶（かん）", vn: "Can, hộp thiếc" },
   { jp: "画面（がめん）", vn: "Màn hình" },
   { jp: "番組（ばんぐみ）", vn: "Chương trình truyền hình" },
   { jp: "記事（きじ）", vn: "Kí sự, phóng sự" },
   { jp: "近所（きんじょ）", vn: "Hàng xóm, vùng lân cận" },
   { jp: "警察（けいさつ）", vn: "Cảnh sát" },
   { jp: "犯人（はんにん）", vn: "Hung thủ, tội phạm" },
   { jp: "小銭（こぜに）", vn: "Tiền lẻ" },
   { jp: "ごちそう（ごちそう）", vn: "Khao, chiêu đãi" },
   { jp: "作者（さくしゃ）", vn: "Tác giả" },
   { jp: "作品（さくひん）", vn: "Tác phẩm" },
   { jp: "制服（せいふく）", vn: "Đồng phục" },
   { jp: "洗剤（せんざい）", vn: "Thuốc tẩy, xà phòng" },
   { jp: "底（そこ）", vn: "Đáy" },
   { jp: "地下（ちか）", vn: "Tầng hầm" },
   { jp: "寺（てら）", vn: "Chùa" },
   { jp: "道路（どうろ）", vn: "Đường lớn" },
   { jp: "坂（さか）", vn: "Dốc, đường dốc" },
   { jp: "煙（けむり）", vn: "Khói" },
   { jp: "灰（はい）", vn: "Tro, tàn" },
   //101-150
   { jp: "判（はん）", vn: "Tem, con dấu" },
   { jp: "名刺（めいし）", vn: "Danh thiếp" },
   { jp: "免許（めんきょ）", vn: "Bằng, giấy phép, chứng chỉ" },
   { jp: "多く（おおく）", vn: "Nhiều" },
   { jp: "前半（ぜんはん）", vn: "Nửa đầu" },
   { jp: "後半（こうはん）", vn: "Nửa cuối" },
   { jp: "最高（さいこう）", vn: "Tốt nhất, tuyệt vời" },
   { jp: "最低（さいてい）", vn: "Thấp nhất, tồi nhất, tối thiểu" },
   { jp: "最初（さいしょ）", vn: "Đầu tiên" },
   { jp: "最後（さいご）", vn: "Cuối cùng" },
   { jp: "自動（じどう）", vn: "Tự động" },
   { jp: "種類（しゅるい）", vn: "Loại, chủng loại" },
   { jp: "性格（せいかく）", vn: "Tính cách" },
   { jp: "性質（せいしつ）", vn: "Tính chất, thuộc tính" },
   { jp: "順番（じゅんばん）", vn: "Thứ tự, lần lượt" },
   { jp: "番（ばん）", vn: "Lượt, số" },
   { jp: "方法（ほうほう）", vn: "Phương pháp" },
   { jp: "製品（せいひん）", vn: "Sản phẩm, hàng hóa" },
   { jp: "値上がり（ねあがり）", vn: "Tăng giá" },
   { jp: "生（なま）", vn: "Tươi, sống" },
   { jp: "渇く（かわく）", vn: "Khát nước, khô nẻ" },
   { jp: "嗅ぐ（かぐ）", vn: "Ngửi" },
   { jp: "叩く（たたく）", vn: "Vỗ, đánh" },
   { jp: "殴る（なぐる）", vn: "Đấm" },
   { jp: "ける（ける）", vn: "Đá" },
   { jp: "抱く（だく）", vn: "Ôm" },
   { jp: "倒れる（たおれる）", vn: "Ngã, đổ" },
   { jp: "倒す（たおす）", vn: "Chặt đổ, lật đổ, đánh gục" },
   { jp: "起きる / 起こる（おきる / おこる）", vn: "Thức dậy, xảy ra" },
   { jp: "起こす（おこす）", vn: "Đánh thức, dựng dậy, gây ra" },
   { jp: "尋ねる（たずねる）", vn: "Hỏi" },
   { jp: "呼ぶ（よぶ）", vn: "Gọi, kêu, gào" },
   { jp: "叫ぶ（さけぶ）", vn: "Kêu, hét, hú" },
   { jp: "黙る（だまる）", vn: "Im lặng" },
   { jp: "飼う（かう）", vn: "Nuôi (động vật)" },
   { jp: "数える（かぞえる）", vn: "Đếm, xếp thứ hạng" },
   { jp: "乾く（かわく）", vn: "Khô" },
   { jp: "乾かす（かわかす）", vn: "Làm khô" },
   { jp: "畳む（たたむ）", vn: "Gấp, gập" },
   { jp: "誘う（さそう）", vn: "Mời" },
   { jp: "おごる（おごる）", vn: "Khao, chiêu đãi" },
   { jp: "預かる（あずかる）", vn: "Trông nom, chăm sóc" },
   { jp: "預ける（あずける）", vn: "Gửi, giao cho, giao phó" },
   { jp: "決まる（きまる）", vn: "Được quyết định" },
   { jp: "決める（きめる）", vn: "Quyết định, làm hoàn chỉnh" },
   { jp: "写る（うつる）", vn: "Chiếu, chụp, phản chiếu" },
   { jp: "写す（うつす）", vn: "Chụp ảnh, chép" },
   { jp: "思い出す（おもいだす）", vn: "Nhớ về, liên tưởng đến" },
   { jp: "教わる（おそわる）", vn: "Học, được dạy" },
   { jp: "申し込む（もうしこむ）", vn: "Đăng ký, yêu cầu, đề nghị, đặt hàng" },
   //151-200
   { jp: "断る（ことわる）", vn: "Từ chối, không chấp nhận" },
   { jp: "見つかる（みつかる）", vn: "Tìm thấy" },
   { jp: "見つける（みつける）", vn: "Tìm kiếm" },
   { jp: "捕まる（つかまる）", vn: "Bị bắt" },
   { jp: "捕まえる（つかまえる）", vn: "Bắt, tóm" },
   { jp: "乗る（のる）", vn: "Lên xe, lên tàu" },
   { jp: "乗せる（のせる）", vn: "Chất lên, chồng lên, xếp lên" },
   { jp: "降りる／下りる（おりる）", vn: "Xuống xe, rơi xuống" },
   { jp: "降ろす／下す（おろす）", vn: "Cho xuống xe, lấy xuống, hạ xuống, rút ra" },
   { jp: "直る（なおる）", vn: "Được sửa" },
   { jp: "直す（なおす）", vn: "Sửa chữa" },
   { jp: "治る（なおる）", vn: "Khỏi bệnh, hồi phục" },
   { jp: "治す（なおす）", vn: "Chữa bệnh" },
   { jp: "亡くなる（なくなる）", vn: "Qua đời" },
   { jp: "亡くす（なくす）", vn: "Chết, mất đi" },
   { jp: "生まれる（うまれる）", vn: "Được sinh ra" },
   { jp: "生む／産む（うむ）", vn: "Sinh, đẻ, tạo nên (kỷ lục)" },
   { jp: "出会う（であう）", vn: "Gặp (tình cờ)" },
   { jp: "訪ねる（たずねる）", vn: "Đến thăm, ghé thăm" },
   { jp: "付き合う（つきあう）", vn: "Đi cùng, hẹn hò" },
   { jp: "効く（きく）", vn: "Có tác dụng, hiệu quả" },
   { jp: "はやる（はやる）", vn: "Lưu hành, thịnh hành" },
   { jp: "経つ（たつ）", vn: "Trải qua, trôi qua" },
   { jp: "間に合う（まにあう）", vn: "Kịp thời, đúng lúc" },
   { jp: "間に合わせる（まにあわせる）", vn: "Làm để kịp" },
   { jp: "通う（かよう）", vn: "Đi học, đi làm, tới lui, hiểu cảm giác" },
   { jp: "込む（こむ）", vn: "Đông đúc" },
   { jp: "すれ違う（すれちがう）", vn: "Lướt qua, vượt qua" },
   { jp: "掛かる（かかる）", vn: "Treo, cần thiết, bắt đầu" },
   { jp: "掛ける（かける）", vn: "Treo, bắt đầu, tốn, chấm, nghe điện thoại" },
   { jp: "動く（うごく）", vn: "Di chuyển, hoạt động" },
   { jp: "動かす（うごかす）", vn: "Vận hành, làm chuyển động" },
   { jp: "離れる（はなれる）", vn: "Rời, chia ly, cách" },
   { jp: "離す（はなす）", vn: "Để xa, tránh xa, làm cách ly" },
   { jp: "ぶつかる（ぶつかる）", vn: "Va vào, đập vào" },
   { jp: "ぶつける（ぶつける）", vn: "Đụng xe, va chạm mạnh" },
   { jp: "こぼれる（こぼれる）", vn: "Bị tràn ra, bị đổ" },
   { jp: "こぼす（こぼす）", vn: "Làm tràn, đánh đổ" },
   { jp: "ふく（ふく）", vn: "Lau, chùi, quét dọn" },
   { jp: "片付く（かたづく）", vn: "Được hoàn thành, được dọn dẹp" },
   { jp: "片付ける（かたづける）", vn: "Dọn, dẹp, cất" },
   { jp: "包む（つつむ）", vn: "Gói ghém, bao bọc" },
   { jp: "張る（はる）", vn: "Dán" },
   { jp: "無くなる（なくなる）", vn: "Mất (đồ, niềm tin, cảm giác, ký ức...)" },
   { jp: "無くす（なくす）", vn: "Làm mất" },
   { jp: "足りる（たりる）", vn: "Đủ" },
   { jp: "残る（のこる）", vn: "Còn lại, sót lại" },
   { jp: "残す（のこす）", vn: "Bỏ lại, sót lại" },
   { jp: "腐る（くさる）", vn: "Thối, ôi thiu" },
   { jp: "むける（むける）", vn: "Được lột, bóc, gọt (vỏ)" },
   //201-250
   { jp: "むく（むく）", vn: "Bóc, lột, gọt" },
   { jp: "滑る（すべる）", vn: "Trượt chân, trượt tay" },
   { jp: "積もる（つもる）", vn: "Chất đống" },
   { jp: "積む（つむ）", vn: "Chồng chất, xếp" },
   { jp: "空く（あく）", vn: "Trống, để không, không dùng" },
   { jp: "空ける（あける）", vn: "Làm cạn, làm rỗng, để trống" },
   { jp: "下がる（さがる）", vn: "Hạ xuống, hạ bớt, giảm đi" },
   { jp: "下げる（さげる）", vn: "Hạ, giảm" },
   { jp: "冷える（ひえる）", vn: "Lạnh đi, nguội đi, cảm thấy lạnh" },
   { jp: "冷やす（ひやす）", vn: "Làm lạnh, hạ nhiệt, giữ bình tĩnh" },
   { jp: "冷める（さめる）", vn: "Nguội đi, lạnh đi" },
   { jp: "冷ます（さます）", vn: "Làm lạnh, làm nguội" },
   { jp: "燃える（もえる）", vn: "Cháy, đốt" },
   { jp: "燃やす（もやす）", vn: "Thiêu đốt, phóng hỏa" },
   { jp: "沸く（わく）", vn: "Sôi lên" },
   { jp: "沸かす（わかす）", vn: "Đun sôi" },
   { jp: "鳴る（なる）", vn: "Reo, gáy, hú, kêu" },
   { jp: "鳴らす（ならす）", vn: "Làm phát ra tiếng kêu" },
   { jp: "役立つ／役に立つ（やくだつ／やくにたつ）", vn: "Có ích, có tác dụng" },
   { jp: "役立てる／役に立てる（やくだてる／やくにたてる）", vn: "Ứng dụng, có tác dụng" },
   { jp: "飾り（かざり）", vn: "Sự trang trí, đồ trang trí" },
   { jp: "遊び（あそび）", vn: "Trò chơi, cách chơi" },
   { jp: "集まり（あつまり）", vn: "Cuộc họp, sự tụ họp" },
   { jp: "教え（おしえ）", vn: "Dạy" },
   { jp: "踊り（おどり）", vn: "Nhảy" },
   { jp: "思い（おもい）", vn: "Suy nghĩ, cảm giác" },
   { jp: "考え（かんがえ）", vn: "Nghĩ, ý tưởng" },
   { jp: "片づけ（かたづけ）", vn: "Dọn dẹp" },
   { jp: "手伝い（てつだい）", vn: "Giúp đỡ" },
   { jp: "働き（はたらき）", vn: "Hoạt động" },
   { jp: "決まり（きまり）", vn: "Luật lệ, quy định, quyết định" },
   { jp: "騒ぎ（さわぎ）", vn: "Ồn ào, om xòm" },
   { jp: "知らせ（しらせ）", vn: "Tin tức, thông báo" },
   { jp: "頼み（たのみ）", vn: "Yêu cầu, đề nghị, nhờ vả" },
   { jp: "疲れ（つかれ）", vn: "Vất vả, mệt mỏi" },
   { jp: "違い（ちがい）", vn: "Khác, sai" },
   { jp: "始め（はじめ）", vn: "Khởi đầu" },
   { jp: "続き（つづき）", vn: "Tiếp tục" },
   { jp: "暮れ（くれ）", vn: "Cuối năm" },
   { jp: "行き（いき）", vn: "Đi" },
   { jp: "帰り（かえり）", vn: "Trở về" },
   { jp: "急ぎ（いそぎ）", vn: "Khẩn cấp, vội" },
   { jp: "遅れ（おくれ）", vn: "Chậm, muộn" },
   { jp: "貸し（かし）", vn: "Cho mượn, cho vay" },
   { jp: "借り（かり）", vn: "Khoản nợ, vay nợ, vay mượn" },
   { jp: "勝ち（かち）", vn: "Thắng" },
   { jp: "負け（まけ）", vn: "Thua" },
   { jp: "迎え（むかえ）", vn: "Đón" },
   { jp: "始まり（はじまり）", vn: "Bắt đầu" },
   { jp: "終わり（おわり）", vn: "Kết thúc" },
   //251-300
   { jp: "戻り（もどり）", vn: "Trở về, trả lại" },
   { jp: "別れ（わかれ）", vn: "Chia ly" },
   { jp: "喜び（よろこび）", vn: "Hớn hở, sung sướng" },
   { jp: "楽しみ（たのしみ）", vn: "Vui mừng, mong mỏi" },
   { jp: "笑い（わらい）", vn: "Cười" },
   { jp: "驚き（おどろき）", vn: "Ngạc nhiên" },
   { jp: "怒り（いかり）", vn: "Giận dữ, phẫn nộ" },
   { jp: "悲しみ（かなしみ）", vn: "Buồn bã" },
   { jp: "幸せ（しあわせ）", vn: "Hạnh phúc" },
   { jp: "得意（とくい）", vn: "Mạnh, giỏi, đắc ý, khoái chí" },
   { jp: "苦手（にがて）", vn: "Yếu, kém" },
   { jp: "熱心な（ねっしんな）", vn: "Chăm chỉ, nhiệt tình, hết mình" },
   { jp: "夢中な（むちゅうな）", vn: "Say sưa, say mê" },
   { jp: "退屈な（たいくつな）", vn: "Chán" },
   { jp: "健康な（けんこうな）", vn: "Khỏe khoắn" },
   { jp: "苦しい（くるしい）", vn: "Khổ" },
   { jp: "平気な（へいきな）", vn: "Bình thản" },
   { jp: "悔しい（くやしい）", vn: "Cay cú, tiếc nuối" },
   { jp: "うらやましい", vn: "Ghen tị, thèm muốn" },
   { jp: "かゆい", vn: "Ngứa" },
   { jp: "おとなしい", vn: "Trầm lặng, hiền, dịu dàng" },
   { jp: "我慢強い（がまんづよい）", vn: "Kiên trì, kiên nhẫn, bền bỉ" },
   { jp: "正直な（しょうじきな）", vn: "Trung thực" },
   { jp: "けちな（けちな）", vn: "Kẹt xỉ" },
   { jp: "わがままな（わがままな）", vn: "Ích kỷ, bướng bỉnh, cố chấp" },
   { jp: "積極的な（せっきょくてきな）", vn: "Tính tích cực" },
   { jp: "消極的な（しょうきょくてきな）", vn: "Tính tiêu cực" },
   { jp: "満足な（まんぞくな）", vn: "Hài lòng" },
   { jp: "不満な（ふまんな）", vn: "Bất mãn" },
   { jp: "不安な（ふあんな）", vn: "Bất an" },
   { jp: "大変な（たいへんな）", vn: "Vất vả" },
   { jp: "無理な（むりな）", vn: "Vô lý, quá sức" },
   { jp: "不注意な（ふちゅういな）", vn: "Không chú ý" },
   { jp: "楽な（らくな）", vn: "Thoải mái" },
   { jp: "面倒な（めんどうな）", vn: "Phiền phức" },
   { jp: "失礼な（しつれいな）", vn: "Thất lễ" },
   { jp: "当然な（とうぜんな）", vn: "Đương nhiên" },
   { jp: "意外な（いがいな）", vn: "Không ngờ đến, ngoài dự tính" },
   { jp: "結構な（けっこうな）", vn: "Tốt, đủ" },
   { jp: "派手な（はでな）", vn: "Lòe loẹt" },
   { jp: "地味な（じみな）", vn: "Giản dị" },
   { jp: "変わった（かわった）", vn: "Thời trang, mốt" },
   { jp: "変な（へんな）", vn: "Lạ" },
   { jp: "不思議な（ふしぎな）", vn: "Kỳ lạ, có ý nghĩa, kỳ quái" },
   { jp: "ましな", vn: "Tốt lên, hơn, thêm, gia tăng" },
   { jp: "むだな", vn: "Lãng phí, không hiệu quả" },
   { jp: "自由な（じゆうな）", vn: "Tự do" },
   { jp: "不自由な（ふじゆうな）", vn: "Tàn tật, không tự do" },
   { jp: "暖まる／温まる（あたたまる）", vn: "Trở nên ấm hơn" },
   { jp: "暖める／温める（あたためる）", vn: "Làm nóng lên, hâm nóng" },
   //301-350
   { jp: "高まる（たかまる）", vn: "Cao lên, được nâng lên" },
   { jp: "高める（たかめる）", vn: "Làm cao lên, nâng cao, dựng" },
   { jp: "強まる（つよまる）", vn: "Mạnh lên, khỏe lên" },
   { jp: "強める（つよめる）", vn: "Làm mạnh lên, khỏe lên" },
   { jp: "弱まる（よわまる）", vn: "Yếu đi" },
   { jp: "弱める（よわめる）", vn: "Làm yếu đi" },
   { jp: "広まる（ひろまる）", vn: "Được lan truyền" },
   { jp: "広める（ひろめる）", vn: "Loan tin, truyền bá" },
   { jp: "深まる（ふかまる）", vn: "Sâu hơn, sâu sắc thêm" },
   { jp: "深める（ふかめる）", vn: "Làm sâu thêm" },
   { jp: "世話（せわ）", vn: "Chăm sóc" },
   { jp: "家庭（かてい）", vn: "Gia đình" },
   { jp: "協力（きょうりょく）", vn: "Hiệp lực" },
   { jp: "感謝（かんしゃ）", vn: "Cảm tạ" },
   { jp: "お礼（おれい）", vn: "Đáp lễ" },
   { jp: "お詫び（おわび）", vn: "Xin lỗi" },
   { jp: "おじぎ（おじぎ）", vn: "Cúi chào" },
   { jp: "握手（あくしゅ）", vn: "Bắt tay" },
   { jp: "いじわる（いじわる）", vn: "Xấu bụng" },
   { jp: "いたずら（いたずら）", vn: "Nghịch ngợm" },
   { jp: "節約（せつやく）", vn: "Tiết kiệm" },
   { jp: "経営（けいえい）", vn: "Kinh doanh" },
   { jp: "反省（はんせい）", vn: "Tự kiểm điểm mình" },
   { jp: "実行（じっこう）", vn: "Thực hành" },
   { jp: "進歩（しんぽ）", vn: "Tiến bộ" },
   { jp: "変化（へんか）", vn: "Thay đổi, biến hóa" },
   { jp: "発達（はったつ）", vn: "Phát triển" },
   { jp: "体力（たいりょく）", vn: "Thể lực" },
   { jp: "出場（しゅつじょう）", vn: "Tham dự, ra mắt, trình diễn" },
   { jp: "活躍（かつやく）", vn: "Hoạt động" },
   { jp: "競争（きょうそう）", vn: "Cạnh tranh, thi đua" },
   { jp: "応援（おうえん）", vn: "Cổ vũ" },
   { jp: "拍手（はくしゅ）", vn: "Vỗ tay" },
   { jp: "人気（にんき）", vn: "Nổi tiếng, được hâm mộ, yêu thích, ưa chuộng" },
   { jp: "うわさ（うわさ）", vn: "Tin đồn" },
   { jp: "情報（じょうほう）", vn: "Thông tin" },
   { jp: "交換（こうかん）", vn: "Trao đổi" },
   { jp: "流行（りゅうこう）", vn: "Trào lưu" },
   { jp: "宣伝（せんでん）", vn: "Tuyên truyền" },
   { jp: "広告（こうこく）", vn: "Quảng cáo" },
   { jp: "注目（ちゅうもく）", vn: "Chú trọng" },
   { jp: "通訳（つうやく）", vn: "Thông dịch" },
   { jp: "翻訳（ほんやく）", vn: "Biên dịch" },
   { jp: "伝言（でんごん）", vn: "Tin nhắn thoại" },
   { jp: "報告（ほうこく）", vn: "Báo cáo" },
   { jp: "録画（ろくが）", vn: "Ghi hình" },
   { jp: "混雑（こんざつ）", vn: "Hỗn tạp, đông đúc" },
   { jp: "渋滞（じゅうたい）", vn: "Tắc đường, tắc nghẽn giao thông" },
   { jp: "衝突（しょうとつ）", vn: "Xung đột" },
   { jp: "被害（ひがい）", vn: "Thiệt hại" },
   //351-400
   { jp: "事故（じこ）", vn: "Tai nạn, sự cố" },
   { jp: "事件（じけん）", vn: "Sự kiện, sự việc" },
   { jp: "故障（こしょう）", vn: "Hỏng hóc" },
   { jp: "修理（しゅうり）", vn: "Sửa chữa" },
   { jp: "停電（ていでん）", vn: "Mất điện" },
   { jp: "調子（ちょうし）", vn: "Trạng thái, tình trạng" },
   { jp: "緊張（きんちょう）", vn: "Lo lắng, căng thẳng" },
   { jp: "自信（じしん）", vn: "Tự tin" },
   { jp: "自慢（じまん）", vn: "Tự mãn" },
   { jp: "感心（かんしん）", vn: "Thán phục, ngưỡng mộ" },
   { jp: "感動（かんどう）", vn: "Cảm động" },
   { jp: "興奮（こうふん）", vn: "Hưng phấn" },
   { jp: "感想（かんそう）", vn: "Cảm tưởng" },
   { jp: "予想（よそう）", vn: "Dự đoán" },
   { jp: "専門（せんもん）", vn: "Chuyên môn" },
   { jp: "研究（けんきゅう）", vn: "Nghiên cứu" },
   { jp: "調査（ちょうさ）", vn: "Điều tra" },
   { jp: "原因（げんいん）", vn: "Nguyên nhân" },
   { jp: "結果（けっか）", vn: "Kết quả" },
   { jp: "解決（かいけつ）", vn: "Giải quyết" },
   { jp: "確認（かくにん）", vn: "Xác nhận" },
   { jp: "利用（りよう）", vn: "Sử dụng" },
   { jp: "理解（りかい）", vn: "Lý giải, hiểu" },
   { jp: "発見（はっけん）", vn: "Phát hiện" },
   { jp: "発明（はつめい）", vn: "Phát minh" },
   { jp: "関係（かんけい）", vn: "Quan hệ" },
   { jp: "団体（だんたい）", vn: "Đoàn thể" },
   { jp: "選挙（せんきょ）", vn: "Bầu cử" },
   { jp: "税金（ぜいきん）", vn: "Thuế" },
   { jp: "責任（せきにん）", vn: "Trách nhiệm" },
   { jp: "書類（しょるい）", vn: "Tài liệu" },
   { jp: "題名（だいめい）", vn: "Tiêu đề" },
   { jp: "条件（じょうけん）", vn: "Điều kiện" },
   { jp: "締め切り（しめきり）", vn: "Hạn cuối" },
   { jp: "期間（きかん）", vn: "Thời gian, thời kỳ" },
   { jp: "倍（ばい）", vn: "Lần, gấp" },
   { jp: "くじ", vn: "Xổ số, rút thăm" },
   { jp: "近道（ちかみち）", vn: "Đường tắt" },
   { jp: "中心（ちゅうしん）", vn: "Trung tâm" },
   { jp: "辺り（あたり）", vn: "Gần, lân cận" },
   { jp: "周り／回り（まわり）", vn: "Xung quanh, vòng quanh" },
   { jp: "穴（あな）", vn: "Lỗ, hang hốc" },
   { jp: "列（れつ）", vn: "Hàng, dãy, đoàn" },
   { jp: "幅（はば）", vn: "Chiều rộng" },
   { jp: "範囲（はんい）", vn: "Phạm vi" },
   { jp: "内容（ないよう）", vn: "Nội dung" },
   { jp: "中身（なかみ）", vn: "Bên trong" },
   { jp: "特徴（とくちょう）", vn: "Đặc trưng" },
   { jp: "普通（ふつう）", vn: "Bình thường, thông thường" },
   { jp: "当たり前（あたりまえ）", vn: "Đương nhiên" },
   //401-450
   { jp: "偽（にせ）", vn: "Giả mạo, bắt chước" },
   { jp: "別（べつ）", vn: "Khác, ngoài ra" },
   { jp: "国籍（こくせき）", vn: "Quốc tịch" },
   { jp: "東洋（とうよう）", vn: "Phương đông" },
   { jp: "西洋（せいよう）", vn: "Phương tây" },
   { jp: "国際（こくさい）", vn: "Quốc tế" },
   { jp: "自然（しぜん）", vn: "Tự nhiên" },
   { jp: "景色（けしき）", vn: "Phong cảnh" },
   { jp: "宗教（しゅうきょう）", vn: "Tôn giáo" },
   { jp: "愛（あい）", vn: "Yêu" },
   { jp: "届く（とどく）", vn: "Đến, đạt được, đụng tới" },
   { jp: "届ける（とどける）", vn: "Đưa đến, chuyển đến" },
   { jp: "かく", vn: "Gãi đầu, gãi ngứa, toát mồ hôi, xấu hổ" },
   { jp: "つかむ", vn: "Nắm, giữ, bắt tóm, nắm bắt (nội dung)" },
   { jp: "握る（にぎる）", vn: "Nắm, túm" },
   { jp: "押さえる（おさえる）", vn: "Giữ, nắm" },
   { jp: "近づく（ちかづく）", vn: "Tiến gần" },
   { jp: "近づける（ちかづける）", vn: "Di chuyển đến gần" },
   { jp: "合う（あう）", vn: "Bắt gặp, hợp, đúng" },
   { jp: "合わせる（あわせる）", vn: "Hợp lại, kết hợp, hợp nhất" },
   { jp: "当たる（あたる）", vn: "Bị đánh" },
   { jp: "当てる（あてる）", vn: "Đánh trúng, bắn trúng" },
   { jp: "比べる（くらべる）", vn: "So sánh" },
   { jp: "似合う（にあう）", vn: "Hợp, xứng, vừa" },
   { jp: "似る（にる）", vn: "Giống" },
   { jp: "似せる（にせる）", vn: "Bắt chước, mô phỏng" },
   { jp: "分かれる（わかれる）", vn: "Được chia ra" },
   { jp: "分ける（わける）", vn: "Chia ra" },
   { jp: "足す（たす）", vn: "Thêm vào, cộng" },
   { jp: "引く（ひく）", vn: "Kéo, rút, bị (cảm), tra (từ điển), gạch chân, trừ" },
   { jp: "増える（ふえる）", vn: "Tăng lên" },
   { jp: "増やす（ふやす）", vn: "Làm tăng lên" },
   { jp: "減る（へる）", vn: "Giảm xuống" },
   { jp: "減らす（へらす）", vn: "Làm giảm xuống" },
   { jp: "変わる（かわる）", vn: "Thay đổi" },
   { jp: "変える（かえる）", vn: "Thay đổi" },
   { jp: "替わる（かわる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "代わる（かわる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "換わる（かわる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "替える（かえる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "代える（かえる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "換える（かえる）", vn: "Thay, thay thế, thay đổi" },
   { jp: "返る（かえる）", vn: "Trả lại" },
   { jp: "返す（かえす）", vn: "Trả lại" },
   { jp: "譲る（ゆずる）", vn: "Nhường, bàn giao" },
   { jp: "助かる（たすかる）", vn: "Được giúp" },
   { jp: "助ける（たすける）", vn: "Giúp đỡ" },
   { jp: "いじめる", vn: "Bắt nạt, ăn hiếp" },
   { jp: "だます", vn: "Lừa, đánh lừa, lừa gạt" },
   { jp: "盗む（ぬすむ）", vn: "Trộm" },
   { jp: "刺さる（ささる）", vn: "Đâm, chích" },
   { jp: "刺す（さす）", vn: "Đâm, chích, châm" },
   { jp: "殺す（ころす）", vn: "Giết hại" },
   { jp: "隠れる（かくれる）", vn: "Lẩn trốn" },
   //451-500
   { jp: "隠す（かくす）", vn: "Bao bọc, che, che giấu, che đậy, giấu, giấu giếm" },
   { jp: "埋まる（うまる）", vn: "Được chôn, bị lấp" },
   { jp: "埋める（うめる）", vn: "Chôn, lấp" },
   { jp: "囲む（かこむ）", vn: "Bao bọc, vây quanh" },
   { jp: "詰まる（つまる）", vn: "Đầy, chặt, tắc, bít, bị ngưng trệ" },
   { jp: "詰める（つめる）", vn: "Lấp, nhét vào, ấn chặt, giảm, rút ngắn" },
   { jp: "開く（ひらく）", vn: "Mở, tổ chức, hoa nở" },
   { jp: "閉じる（とじる）", vn: "Đóng" },
   { jp: "飛ぶ（とぶ）", vn: "Bay, truyền bá" },
   { jp: "飛ばす（とばす）", vn: "Bay, thổi đi, bắn, phóng" },
   { jp: "振る（ふる）", vn: "Vẫy, lắc, rắc" },
   { jp: "めくる", vn: "Lật lên, bóc" },
   { jp: "見かける（みかける）", vn: "Thông báo, yết thị, tìm ra, bắt gặp" },
   { jp: "確かめる（たしかめる）", vn: "Xác nhận, kiểm tra" },
   { jp: "試す（ためす）", vn: "Thử nghiệm, thí nghiệm" },
   { jp: "繰り返す（くりかえす）", vn: "Lặp lại" },
   { jp: "訳す（やくす）", vn: "Dịch (phiên dịch, thông dịch)" },
   { jp: "行う（おこなう）", vn: "Tổ chức sự kiện" },
   { jp: "間違う（まちがう）", vn: "Sai, không đúng" },
   { jp: "間違える（まちがえる）", vn: "Sai, nhầm lẫn, làm không đúng" },
   { jp: "許す（ゆるす）", vn: "Cho phép, tha thứ" },
   { jp: "慣れる（なれる）", vn: "Quen, quen với, trở nên quen với" },
   { jp: "慣らす（ならす）", vn: "Làm cho quen" },
   { jp: "立つ（たつ）", vn: "Đứng, đứng lên" },
   { jp: "立てる（たてる）", vn: "Dựng lên, lập lên" },
   { jp: "建つ（たつ）", vn: "Được xây dựng, được mọc lên" },
   { jp: "建てる（たてる）", vn: "Xây dựng" },
   { jp: "育つ（そだつ）", vn: "Lớn lên, lớn khôn, phát triển" },
   { jp: "育てる（そだてる）", vn: "Nuôi dưỡng, nuôi lớn" },
   { jp: "生える（はえる）", vn: "Mọc (răng), phát triển, sinh sôi" },
   { jp: "生やす（はやす）", vn: "Nuôi cấy, trồng trọt" },
   { jp: "汚れる（よごれる）", vn: "Ô nhiễm" },
   { jp: "汚す（よごす）", vn: "Làm ô nhiễm, làm bẩn" },
   { jp: "壊れる（こわれる）", vn: "Hỏng, bị hỏng" },
   { jp: "壊す（こわす）", vn: "Làm hỏng" },
   { jp: "割れる（われる）", vn: "Bị vỡ vụn" },
   { jp: "割る（わる）", vn: "Đập vỡ, chia ra, cắt nhỏ, đập nát" },
   { jp: "折れる（おれる）", vn: "Bị gãy" },
   { jp: "折る（おる）", vn: "Bẻ gãy" },
   { jp: "破れる（やぶれる）", vn: "Bị rách" },
   { jp: "破る（やぶる）", vn: "Làm rách, xé rách, phá vỡ kỉ lục" },
   { jp: "曲がる（まがる）", vn: "Bị gập, bị uốn cong" },
   { jp: "曲げる（まげる）", vn: "Gập, uốn cong" },
   { jp: "外れる（はずれる）", vn: "Tuột ra, chệch ra, rời ra" },
   { jp: "外す（はずす）", vn: "Làm tuột ra, tháo ra" },
   { jp: "揺れる（ゆれる）", vn: "Bập bềnh, chệnh choạng, dao động" },
   { jp: "揺らす（ゆらす）", vn: "Làm dao động, làm lung lay" },
   { jp: "流れる（ながれる）", vn: "Chảy, nước trôi, trôi tuột, được lan truyền" },
   { jp: "流す（ながす）", vn: "Làm lan truyền (tiếng đồn), làm cho chảy đi" },
   { jp: "濡れる（ぬれる）", vn: "Bị ướt, dính, đẫm" },
   //501-550
   { jp: "濡らす（ぬらす）", vn: "Làm ướt" },
   { jp: "迷う（まよう）", vn: "Bị lúng túng, không hiểu" },
   { jp: "悩む（なやむ）", vn: "Khổ, lo lắng, buồn phiền" },
   { jp: "慌てる（あわてる）", vn: "Trở nên lộn xộn, hốt hoảng, bối rối" },
   { jp: "覚める（さめる）", vn: "Tỉnh dậy, thức giấc" },
   { jp: "覚ます（さます）", vn: "Đánh thức, làm tỉnh giấc" },
   { jp: "眠る（ねむる）", vn: "Ngủ" },
   { jp: "祈る（いのる）", vn: "Cầu nguyện" },
   { jp: "祝う（いわう）", vn: "Chúc mừng" },
   { jp: "感じる（かんじる）", vn: "Cảm giác, cảm thấy" },
   { jp: "クラスメート", vn: "Bạn cùng lớp" },
   { jp: "グループ", vn: "Nhóm" },
   { jp: "チーム", vn: "Đội" },
   { jp: "プロフェッショナル", vn: "Chuyên nghiệp" },
   { jp: "アマチュア", vn: "Nghiệp dư" },
   { jp: "トレーニング", vn: "Đào tạo, luyện tập" },
   { jp: "マッサージ", vn: "Mát xa" },
   { jp: "アドバイス", vn: "Khuyên" },
   { jp: "アイデア", vn: "Ý tưởng" },
   { jp: "アイディア", vn: "Ý tưởng" },
   { jp: "トップ", vn: "Đứng đầu" },
   { jp: "スピード", vn: "Tốc độ" },
   { jp: "ラッシュ", vn: "Giờ cao điểm" },
   { jp: "バイク", vn: "Xe máy" },
   { jp: "ヘルメット", vn: "Mũ bảo hiểm" },
   { jp: "コンタクトレンズ", vn: "Kính áp tròng" },
   { jp: "ガラス", vn: "Kính, thủy tinh" },
   { jp: "プラスチック", vn: "Nhựa" },
   { jp: "ベランダ", vn: "Ban công" },
   { jp: "ペット", vn: "Thú cưng" },
   { jp: "ベンチ", vn: "Ghế" },
   { jp: "デザイン", vn: "Thiết kế" },
   { jp: "バーゲンセール", vn: "Sale, giảm giá" },
   { jp: "パート", vn: "Làm thêm" },
   { jp: "コンビニエンスストア", vn: "Cửa hàng tiện ích" },
   { jp: "レジ", vn: "Tính tiền" },
   { jp: "レシート", vn: "Hóa đơn, biên lai" },
   { jp: "インスタント", vn: "Ăn liền" },
   { jp: "ファストフード", vn: "Đồ ăn nhanh" },
   { jp: "フルーツ", vn: "Trái cây" },
   { jp: "デザート", vn: "Tráng miệng" },
   { jp: "インターネット", vn: "Internet" },
   { jp: "チャイム", vn: "Chuông" },
   { jp: "アナウンス", vn: "Thông báo" },
   { jp: "メッセージ", vn: "Tin nhắn" },
   { jp: "パンフレット", vn: "Tờ rơi" },
   { jp: "カード", vn: "Card, thẻ" },
   { jp: "インタビュー", vn: "Phỏng vấn" },
   { jp: "アンケート", vn: "Tờ câu hỏi, bản điều tra" },
   { jp: "データ", vn: "Dữ liệu" },
   { jp: "パーセント", vn: "Tỉ lệ %" },
   //551-600
   { jp: "濃い（こい）", vn: "Đậm, đặc, quan hệ gần gũi" },
   { jp: "薄い（うすい）", vn: "Mỏng, nhạt" },
   { jp: "酸っぱい（すっぱい）", vn: "Chua" },
   { jp: "臭い（くさい）", vn: "Thối, mùi, hơi" },
   { jp: "おかしい", vn: "Lạ, lố bịch, buồn cười" },
   { jp: "かっこいい", vn: "Bảnh bao, ngầu" },
   { jp: "うまい", vn: "Ngon, khéo, tài giỏi" },
   { jp: "親しい（したしい）", vn: "Thân thiết" },
   { jp: "詳しい（くわしい）", vn: "Chi tiết" },
   { jp: "細かい（こまかい）", vn: "Tiểu tiết, bé" },
   { jp: "浅い（あさい）", vn: "Nông cạn, hời hợt" },
   { jp: "固い・硬い（かたい）", vn: "Cứng, bảo thủ, vững chắc" },
   { jp: "ぬるい", vn: "Nguội, ấm" },
   { jp: "まぶしい", vn: "Chói" },
   { jp: "蒸し暑い（むしあつい）", vn: "Nóng ẩm, oi bức" },
   { jp: "清潔な（せいけつな）", vn: "Sạch sẽ, thanh khiết" },
   { jp: "新鮮な（しんせんな）", vn: "Tươi mới" },
   { jp: "豊かな（ゆたかな）", vn: "Giàu có" },
   { jp: "立派な（りっぱな）", vn: "Siêu, tuyệt vời" },
   { jp: "正確な（せいかくな）", vn: "Chính xác" },
   { jp: "確かな（たしかな）", vn: "Đích thực" },
   { jp: "重要な（じゅうような）", vn: "Quan trọng" },
   { jp: "必要な（ひつような）", vn: "Cần thiết" },
   { jp: "もったいない", vn: "Lãng phí" },
   { jp: "すごい", vn: "Ghê, siêu, tuyệt vời, giỏi" },
   { jp: "ひどい", vn: "Tồi tệ, khủng khiếp" },
   { jp: "激しい（はげしい）", vn: "Mãnh liệt" },
   { jp: "そっくりな", vn: "Giống y đúc" },
   { jp: "急な（きゅうな）", vn: "Đột nhiên, khẩn cấp, khẩn trương" },
   { jp: "適当な（てきとうな）", vn: "Phù hợp" },
   { jp: "特別な（とくべつな）", vn: "Đặc biệt" },
   { jp: "完全な（かんぜんな）", vn: "Toàn bộ, nguyên vẹn" },
   { jp: "盛んな（さかんな）", vn: "Thịnh vượng" },
   { jp: "様々な（さまざまな）", vn: "Đa dạng" },
   { jp: "可能な（かのうな）", vn: "Khả năng" },
   { jp: "不可能な（ふかのうな）", vn: "Không có khả năng" },
   { jp: "基本的な（きほんてきな）", vn: "Cơ bản, tiêu chuẩn" },
   { jp: "国際的な（こくさいてきな）", vn: "Tính quốc tế" },
   { jp: "ばらばらな", vn: "Tung tóe, chia rẽ, riêng biệt" },
   { jp: "ぼろぼろな", vn: "Rách nát, te tua" },
   { jp: "非常に（ひじょうに）", vn: "Khẩn cấp, cực kỳ, rất,..." },
   { jp: "大変(に)（たいへんに）", vn: "Khủng khiếp, rất nhiều" },
   { jp: "ほとんど", vn: "Hầu hết, gần như" },
   { jp: "大体（だいたい）", vn: "Đại khái, ước chừng" },
   { jp: "かなり", vn: "Kha khá, tương đối" },
   { jp: "ずいぶん", vn: "Đáng kể, rất nhiều, vô cùng" },
   { jp: "けっこう", vn: "Tạm được, tương đối, đủ" },
   { jp: "大分（だいぶ）", vn: "Chủ yếu, khá, nhiều" },
   { jp: "もっと", vn: "Hơn, nữa" },
   { jp: "しっかり", vn: "Toàn bộ" },
   //601-650
   { jp: "一杯（いっぱい）", vn: "Đầy" },
   { jp: "ぎりぎり", vn: "Gần, sát nút" },
   { jp: "ぴったり（と）", vn: "Vừa vặn, đúng" },
   { jp: "たいてい", vn: "Đại thể, thường" },
   { jp: "同時に（どうじに）", vn: "Cùng lúc" },
   { jp: "前もって（まえもって）", vn: "Trước" },
   { jp: "すぐ（に）", vn: "Ngay lập tức" },
   { jp: "もうすぐ", vn: "Sắp" },
   { jp: "突然（とつぜん）", vn: "Đột nhiên" },
   { jp: "あっという間（に）（あっというまに）", vn: "Loáng một cái" },
   { jp: "いつの間にか（いつのまにか）", vn: "Lúc nào không biết" },
   { jp: "しばらく", vn: "Một chút" },
   { jp: "ずっと", vn: "Suốt, nhiều" },
   { jp: "相変わらず（あいかわらず）", vn: "Như mọi khi" },
   { jp: "次々に／と（つぎつぎに／と）", vn: "Lần lượt" },
   { jp: "どんどん", vn: "Dần dần" },
   { jp: "ますます", vn: "Càng ngày càng" },
   { jp: "やっと", vn: "Cuối cùng, vừa đủ" },
   { jp: "とうとう", vn: "Sau cùng, cuối cùng, sau tất cả" },
   { jp: "ついに", vn: "Cuối cùng, sau cùng" },
   { jp: "もちろん", vn: "Tất nhiên" },
   { jp: "やはり", vn: "Như dự tính" },
   { jp: "きっと", vn: "Nhất định" },
   { jp: "ぜひ", vn: "Bằng mọi giá, rất (muốn)" },
   { jp: "なるべく", vn: "Càng nhiều càng tốt" },
   { jp: "案外（あんがい）", vn: "Không ngờ đến" },
   { jp: "もしかすると", vn: "Có lẽ" },
   { jp: "もしかしたら", vn: "Không thể ngờ, không" },
   { jp: "もしかして", vn: "Ngơ ngác, không để ý" },
   { jp: "まさか", vn: "Vô ý, buột" },
   { jp: "うっかり", vn: "Không ngờ đến" },
   { jp: "つい", vn: "Yên tâm" },
   { jp: "思わず（おもわず）", vn: "Khó chịu, nóng giận" },
   { jp: "ほっと", vn: "Tận hưởng" },
   { jp: "いらいら", vn: "Thực tế là" },
   { jp: "のんびり", vn: "Đọc viết" },
   { jp: "実は（じつは）", vn: "Biểu diễn" },
   { jp: "読書（どくしょ）", vn: "Nghệ thuật" },
   { jp: "演奏（えんそう）", vn: "Kiểm tra" },
   { jp: "芸術（げいじゅつ）", vn: "Máu" },
   { jp: "検査（けんさ）", vn: "Trị liệu" },
   { jp: "血液（けつえき）", vn: "Triệu chứng" },
   { jp: "治療（ちりょう）", vn: "Dự phòng" },
   { jp: "症状（しょうじょう）", vn: "Dinh dưỡng" },
   { jp: "予防（よぼう）", vn: "Phẫu thuật" },
   { jp: "栄養（えいよう）", vn: "Tử vong" },
   { jp: "手術（しゅじゅつ）", vn: "Sinh mạng" },
   { jp: "死亡（しぼう）", vn: "Suốt đời" },
   { jp: "命（いのち）", vn: "Hiểu nhầm" },
   { jp: "一生（いっしょう）", vn: "Suốt đời" },
   { jp: "誤解（ごかい）", vn: "Hiểu nhầm" },
   { jp: "後悔（こうかい）", vn: "Hối hận" },
   //651-700
   { jp: "訳（わけ）", vn: "Lý do" },
   { jp: "態度（たいど）", vn: "Thái độ" },
   { jp: "癖（くせ）", vn: "Thói quen" },
   { jp: "礼儀（れいぎ）", vn: "Lễ nghĩa" },
   { jp: "文句（もんく）", vn: "Phàn nàn" },
   { jp: "表情（ひょうじょう）", vn: "Biểu lộ, biểu thị" },
   { jp: "鏡面（きょうめん）", vn: "Bề mặt" },
   { jp: "禁煙（きんえん）", vn: "Cấm hút thuốc" },
   { jp: "禁止（きんし）", vn: "Cấm" },
   { jp: "完成（かんせい）", vn: "Hoàn thành" },
   { jp: "課題（かだい）", vn: "Chủ đề" },
   { jp: "例外（れいがい）", vn: "Ngoại lệ" },
   { jp: "基本（きほん）", vn: "Cơ bản" },
   { jp: "記録（きろく）", vn: "Ghi chép, kỷ lục" },
   { jp: "状態（じょうたい）", vn: "Trạng thái" },
   { jp: "出来事（できごと）", vn: "Sự kiện" },
   { jp: "場面（ばめん）", vn: "Khung cảnh, tình huống, hiện trường" },
   { jp: "機会（きかい）", vn: "Cơ hội" },
   { jp: "距離（きょり）", vn: "Khoảng cách" },
   { jp: "提案（ていあん）", vn: "Đề xuất" },
   { jp: "やり取り（やりとり）", vn: "Trao đổi, làm việc" },
   { jp: "知識（ちしき）", vn: "Kiến thức" },
   { jp: "実力（じつりょく）", vn: "Thực lực" },
   { jp: "手段（しゅだん）", vn: "Cách thức" },
   { jp: "代表（だいひょう）", vn: "Đại biểu" },
   { jp: "影響（えいきょう）", vn: "Ảnh hưởng" },
   { jp: "効果（こうか）", vn: "Hiệu quả" },
   { jp: "印象（いんしょう）", vn: "Ấn tượng" },
   { jp: "印（しるし）", vn: "Dấu, dấu hiệu" },
   { jp: "合図（あいず）", vn: "Ám hiệu" },
   { jp: "共通（きょうつう）", vn: "Chung" },
   { jp: "強調（きょうちょう）", vn: "Nhấn mạnh" },
   { jp: "省略（しょうりゃく）", vn: "Lược bớt" },
   { jp: "挑戦（ちょうせん）", vn: "Thử thách" },
   { jp: "やる気（やるき）", vn: "Động lực" },
   { jp: "勇気（ゆうき）", vn: "Dũng cảm, dũng khí" },
   { jp: "資格（しかく）", vn: "Bằng cấp, tư cách" },
   { jp: "申請（しんせい）", vn: "Đăng ký, ứng tuyển" },
   { jp: "本人（ほんにん）", vn: "Người được nói đến" },
   { jp: "契約（けいやく）", vn: "Hợp đồng" },
   { jp: "証明（しょうめい）", vn: "Chứng minh, bằng chứng" },
   { jp: "変更（へんこう）", vn: "Thay đổi" },
   { jp: "保存（ほぞん）", vn: "Bảo tồn" },
   { jp: "保護（ほご）", vn: "Bảo vệ" },
   { jp: "環境（かんきょう）", vn: "Môi trường" },
   { jp: "資源（しげん）", vn: "Tài nguyên" },
   { jp: "不足（ふそく）", vn: "Thiếu" },
   { jp: "平均（へいきん）", vn: "Trung bình" },
   { jp: "割合（わりあい）", vn: "Tỷ lệ" },
   { jp: "商売（しょうばい）", vn: "Kinh doanh, buôn bán" },
   //701-750
   { jp: "商品（しょうひん）", vn: "Sản phẩm" },
   { jp: "質（しつ）", vn: "Chất lượng" },
   { jp: "型（かた）", vn: "Mẫu, kiểu dáng" },
   { jp: "生産（せいさん）", vn: "Sản xuất" },
   { jp: "消費（しょうひ）", vn: "Tiêu dùng, tiêu thụ" },
   { jp: "物価（ぶっか）", vn: "Giá cả, vật giá" },
   { jp: "倒産（とうさん）", vn: "Phá sản" },
   { jp: "携帯（けいたい）", vn: "Mang theo, di động" },
   { jp: "現代（げんだい）", vn: "Hiện đại" },
   { jp: "世紀（せいき）", vn: "Thế kỷ" },
   { jp: "文化（ぶんか）", vn: "Văn hóa" },
   { jp: "都市（とし）", vn: "Thành phố" },
   { jp: "地方（ちほう）", vn: "Địa phương" },
   { jp: "戦争（せんそう）", vn: "Chiến tranh" },
   { jp: "平和（へいわ）", vn: "Hòa bình" },
   { jp: "上る（のぼる）", vn: "Leo lên" },
   { jp: "下る（くだる）", vn: "Đi xuống" },
   { jp: "進む（すすむ）", vn: "Tiến lên" },
   { jp: "進める（すすめる）", vn: "Làm cho tiến lên, thúc đẩy" },
   { jp: "通る（とおる）", vn: "Đi qua, thông qua, được chấp nhận" },
   { jp: "通す（とおす）", vn: "Xuyên qua, cho qua, thông qua" },
   { jp: "越える／超える（こえる）", vn: "Vượt qua" },
   { jp: "過ぎる（すぎる）", vn: "Quá, đi qua" },
   { jp: "過ごす（すごす）", vn: "Trải qua, sử dụng (thời gian)" },
   { jp: "移る（うつる）", vn: "Được chuyển, di chuyển" },
   { jp: "移す（うつす）", vn: "Chuyển, di chuyển" },
   { jp: "連れる（つれる）", vn: "Dẫn đi, dẫn theo" },
   { jp: "寄る（よる）", vn: "Ghé sát, lại gần, ghé qua" },
   { jp: "寄せる（よせる）", vn: "Ghé vào, tấp vào, tiến lại gần" },
   { jp: "与える（あたえる）", vn: "Trao, cung cấp, ban cho" },
   { jp: "得る（える）", vn: "Đạt được, có được" },
   { jp: "向く（むく）", vn: "Hướng, đối diện, phù hợp" },
   { jp: "向ける（むける）", vn: "Hướng đến, quay về phía" },
   { jp: "勧める（すすめる）", vn: "Khuyên bảo, gợi ý, rủ" },
   { jp: "薦める（すすめる）", vn: "Giới thiệu, đề xuất" },
   { jp: "任せる（まかせる）", vn: "Giao phó, để cho ai đó làm gì" },
   { jp: "守る（まもる）", vn: "Giữ, tuân thủ, bảo vệ" },
   { jp: "争う（あらそう）", vn: "Tranh giành, cãi cọ, gây gổ" },
   { jp: "望む（のぞむ）", vn: "Mong muốn, ước" },
   { jp: "信じる（しんじる）", vn: "Tin tưởng" },
   { jp: "通じる（つうじる）", vn: "Hiểu, thông qua, kết nối" },
   { jp: "飽きる（あきる）", vn: "Chán, ngấy" },
   { jp: "思いつく（おもいつく）", vn: "Nghĩ ra, nảy ra ý" },
   { jp: "思いやる（おもいやる）", vn: "Quan tâm, thông cảm" },
   { jp: "熱中する（ねっちゅうする）", vn: "Say mê, nghiện" },
   { jp: "暮らす（くらす）", vn: "Sống, sinh hoạt" },
   { jp: "巻く（まく）", vn: "Quấn, cuộn, quàng" },
   { jp: "結ぶ（むすぶ）", vn: "Buộc, cột, nối" },
   { jp: "済む（すむ）", vn: "Kết thúc, hoàn thành" },
   { jp: "済ませる（すませる）", vn: "Hoàn tất, làm xong" },
   { jp: "済ます（すます）", vn: "Kết thúc, xong xuôi" },
   //751-800
   { jp: "出来る（できる）", vn: "Có thể, được xây dựng" },
   { jp: "切れる（きれる）", vn: "Cắt, hết hạn" },
   { jp: "切らす（きらす）", vn: "Hết (dùng hết thứ gì đó)" },
   { jp: "伝わる（つたわる）", vn: "Được truyền đi, lan truyền, được giới thiệu" },
   { jp: "伝える（つたえる）", vn: "Truyền đạt, giới thiệu, nhắn lại" },
   { jp: "続く（つづく）", vn: "Tiếp tục, xảy ra, lặp lại, theo sau" },
   { jp: "続ける（つづける）", vn: "Tiếp tục, làm liên tục" },
   { jp: "つながる", vn: "Được kết nối, được mở rộng, thông qua" },
   { jp: "つなぐ", vn: "Kết nối, tham gia, nối lại" },
   { jp: "つなげる", vn: "Kết nối, làm chặt thêm, gắn kết" },
   { jp: "伸びる（のびる）", vn: "Lớn lên, tăng thêm, dài ra" },
   { jp: "伸ばす（のばす）", vn: "Nuôi dài, kéo dài, phát triển" },
   { jp: "延びる（のびる）", vn: "Bị trì hoãn, bị kéo dài" },
   { jp: "延ばす（のばす）", vn: "Trì hoãn, kéo dài" },
   { jp: "重なる（かさなる）", vn: "Xung đột, chồng chất, trùng nhau" },
   { jp: "重ねる（かさねる）", vn: "Chồng lên, tích trữ, lặp lại" },
   { jp: "広がる（ひろがる）", vn: "Mở rộng, lan tràn, trải dài" },
   { jp: "広げる（ひろげる）", vn: "Mở rộng, nới ra, trải ra" },
   { jp: "載る（のる）", vn: "Được đăng tải, vừa, được đặt lên" },
   { jp: "載せる（のせる）", vn: "Cho lên, đăng tải, công bố" },
   { jp: "そろう", vn: "Thu thập, được tập hợp, đầy đủ" },
   { jp: "そろえる", vn: "Gom lại, chuẩn bị sẵn sàng, làm cho đồng đều" },
   { jp: "まとまる", vn: "Được thống nhất, được sắp xếp, được tổ chức" },
   { jp: "まとめる", vn: "Tập hợp, sắp xếp, hợp nhất, tổng kết" },
   { jp: "付く（つく）", vn: "Dính, gắn, đạt được, đi kèm với" },
   { jp: "付ける（つける）", vn: "Gắn, thêm vào" },
   { jp: "たまる", vn: "Được tiết kiệm, tích trữ" },
   { jp: "ためる", vn: "Tiết kiệm, dành dụm" },
   { jp: "交じる（まじる）", vn: "Giao vào, lẫn vào" },
   { jp: "混じる（まじる）", vn: "Được trộn lẫn, hòa vào" },
   { jp: "交ざる（まざる）", vn: "Trộn vào, xen lẫn" },
   { jp: "混ざる（まざる）", vn: "Được trộn vào, hòa lẫn" },
   { jp: "交ぜる（まぜる）", vn: "Trộn, pha trộn (các thứ khác nhau)" },
   { jp: "混ぜる（まぜる）", vn: "Trộn, khuấy, hòa" },
   { jp: "解ける（とける）", vn: "Được giải quyết, được tháo gỡ, tan chảy" },
   { jp: "溶ける（とける）", vn: "Tan chảy, hòa tan" },
   { jp: "解く（とく）", vn: "Giải quyết, tháo gỡ (vấn đề, câu đố...)" },
   { jp: "溶く（とく）", vn: "Khuấy, đánh tan (trứng, bột...)" },
   { jp: "溶かす（とかす）", vn: "Làm tan chảy, hòa tan" },
   { jp: "含む（ふくむ）", vn: "Chứa, bao gồm" },
   { jp: "含める（ふくめる）", vn: "Bao gồm, tính cả vào" },
   { jp: "抜ける（ぬける）", vn: "Tháo ra, tuột ra, rơi ra" },
   { jp: "抜く（ぬく）", vn: "Rút ra, nhổ ra, lấy ra" },
   { jp: "現れる（あらわれる）", vn: "Xuất hiện, được thể hiện" },
   { jp: "現す（あらわす）", vn: "Xuất hiện, biểu lộ, cho thấy" },
   { jp: "表れる（あらわれる）", vn: "Biểu hiện (trên mặt, thái độ...)" },
   { jp: "表す（あらわす）", vn: "Biểu thị, diễn đạt, đại diện" },
   { jp: "散る（ちる）", vn: "Bị tàn, rụng (hoa...)" },
   { jp: "散らす（ちらす）", vn: "Làm rơi, làm bay, rải rác" },
   { jp: "明ける（あける）", vn: "(Đêm) đến, (năm mới) bắt đầu, (mùa mưa) kết thúc" },
   { jp: "差す（さす）", vn: "(Mặt trời) chiếu sáng, mở (ô), nhỏ (thuốc mắt)" },
   { jp: "パートナー", vn: "Đối tác, bạn đời" },
   { jp: "リーダー", vn: "Lãnh đạo, người dẫn đầu" },
   { jp: "ボランティア", vn: "Tình nguyện viên, tình nguyện" },
   { jp: "コミュニケーション（こみゅにけーしょん）", vn: "Giao tiếp" },
   //801-850
   { jp: "ユーモア（ゆーもあ）", vn: "Hài hước, đùa" },
   { jp: "ショック（しょっく）", vn: "Cú sốc, choáng" },
   { jp: "ストレス（すとれす）", vn: "Căng thẳng, stress" },
   { jp: "バランス（ばらんす）", vn: "Cân bằng" },
   { jp: "レベル（れべる）", vn: "Trình độ, cấp độ" },
   { jp: "アップ（あっぷ）", vn: "Tăng lên, nâng cao" },
   { jp: "ダウン（だうん）", vn: "Giảm xuống, hạ xuống" },
   { jp: "プラス（ぷらす）", vn: "Phép cộng, tác động tích cực" },
   { jp: "マイナス（まいなす）", vn: "Phép trừ, tác động tiêu cực" },
   { jp: "イメージ（いめーじ）", vn: "Hình ảnh" },
   { jp: "コンテスト（こんてすと）", vn: "Cuộc thi" },
   { jp: "マスコミ（ますこみ）", vn: "Truyền thông, báo chí" },
   { jp: "プライバシー（ぷらいばしー）", vn: "Sự riêng tư, cá nhân" },
   { jp: "オフィス（おふぃす）", vn: "Văn phòng" },
   { jp: "ルール（るーる）", vn: "Luật lệ, quy tắc" },
   { jp: "マナー（まなー）", vn: "Kiểu, thói quen, phép lịch sự" },
   { jp: "ミス（みす）", vn: "Lỗi, sai sót" },
   { jp: "スケジュール（すけじゅーる）", vn: "Lịch, kế hoạch" },
   { jp: "タイトル（たいとる）", vn: "Tiêu đề" },
   { jp: "テーマ（てーま）", vn: "Chủ đề" },
   { jp: "ストーリー（すとーりー）", vn: "Câu chuyện" },
   { jp: "ヒット（ひっと）", vn: "Nổi tiếng, ăn khách" },
   { jp: "ブランド（ぶらんど）", vn: "Nhãn hiệu, thương hiệu" },
   { jp: "レンタル（れんたる）", vn: "Thuê, cho thuê" },
   { jp: "リサイクル（りさいくる）", vn: "Tái chế" },
   { jp: "ラベル（らべる）", vn: "Nhãn" },
   { jp: "タイプ（たいぷ）", vn: "Loại" },
   { jp: "スタイル（すたいる）", vn: "Kiểu dáng" },
   { jp: "セット（せっと）", vn: "Cài đặt, bộ, set" },
   { jp: "ウイルス（ういるす）", vn: "Vi-rút" },
   { jp: "ロボット（ろぼっと）", vn: "Người máy, robot" },
   { jp: "エネルギー（えねるぎー）", vn: "Năng lượng" },
   { jp: "デジタル（でじたる）", vn: "Kỹ thuật số" },
   { jp: "マイク（まいく）", vn: "Microphone, ghi âm" },
   { jp: "ブレーキ（ぶれーき）", vn: "Phanh" },
   { jp: "ペンキ（ぺんき）", vn: "Sơn" },
   { jp: "炊ける（たける）", vn: "Được nấu" },
   { jp: "炊く（たく）", vn: "Nấu (cơm)" },
   { jp: "煮える（にえる）", vn: "Được nấu, được ninh" },
   { jp: "煮る（にる）", vn: "Nấu, ninh, luộc" },
   { jp: "炒める（いためる）", vn: "Rán, xào" },
   { jp: "焼ける（やける）", vn: "Được nấu, được nướng" },
   { jp: "焼く（やく）", vn: "Nướng, nấu" },
   { jp: "ゆでる（ゆでる）", vn: "Luộc" },
   { jp: "揚げる（あげる）", vn: "Rán ngập (chiên)" },
   { jp: "蒸す（むす）", vn: "Hấp" },
   { jp: "ぐっすり（ぐっすり）", vn: "Ngủ say, nói" },
   { jp: "きちんと（きちんと）", vn: "Ngay ngắn, chỉnh tề" },
   { jp: "しっかり（しっかり）", vn: "Kiên quyết, chắc chắn, đáng tin cậy" },
   { jp: "はっきり（はっきり）", vn: "Rõ ràng" },
   { jp: "じっと（じっと）", vn: "Kiên nhẫn, chăm chú, chằm chằm" },
   //851
   { jp: "そっと（そっと）", vn: "Nhẹ nhàng, yên lặng" },
   { jp: "別々に（べつべつに）", vn: "Riêng biệt" },
   { jp: "それぞれ（それぞれ）", vn: "Lần lượt, tương ứng" },
   { jp: "互いに（たがいに）", vn: "Lẫn nhau" },
   { jp: "直接（ちょくせつ）", vn: "Trực tiếp" },
   { jp: "本当に（ほんとうに）", vn: "Thật lòng, kỳ thực" },
   { jp: "必ず（かならず）", vn: "Chắc chắn" },
   { jp: "絶対に（ぜったいに）", vn: "Chắc chắn rồi, tuyệt đối" },
   { jp: "特に（とくに）", vn: "Đặc biệt là" },
   { jp: "ただ（ただ）", vn: "Chỉ" },
   { jp: "少なくとも（すくなくとも）", vn: "Ít nhất" },
   { jp: "決して（けっして）", vn: "Không bao giờ" },
   { jp: "少しも（すこしも）", vn: "(Không) một chút" },
   { jp: "ちっとも（ちっとも）", vn: "(Không) tí gì" },
   { jp: "全く（まったく）", vn: "Hoàn toàn (không)" },
   { jp: "とても（とても）", vn: "Rất" },
   { jp: "どんなに（どんなに）", vn: "Thế nào, bao nhiêu" },
   { jp: "どうしても（どうしても）", vn: "Kiểu gì cũng, dù thế nào cũng" },
   { jp: "まるで（まるで）", vn: "Giống hệt như" },
   { jp: "一体（いったい）", vn: "Cái quái gì, rốt cuộc là" },
   { jp: "別に（べつに）", vn: "(Không) có gì, ngoài ra" },
   { jp: "たった（たった）", vn: "Chỉ, mỗi" },
   { jp: "ほんの（ほんの）", vn: "Một chút, chỉ là" },
   { jp: "それで（それで）", vn: "Do đó, bởi vậy" },
   { jp: "そこで（そこで）", vn: "Tiếp theo, vì vậy mà" },
   { jp: "その上（そのうえ）", vn: "Bên cạnh đó, ngoài ra, hơn thế nữa" },
   { jp: "また（また）", vn: "Lại còn, và, ngoài ra, hơn nữa" },
   { jp: "または（または）", vn: "Hoặc, nếu không thì" },
   { jp: "それとも（それとも）", vn: "Hoặc, hay, hay là" },
   { jp: "つまり（つまり）", vn: "Nói cách khác, tóm lại là, tức là" },
];


